### ISSUE TITLE
Readme install is not actual

### ISSUE THREAD

**Issue by DanielWielanek** [FairRootGroup/FairRoot#1009]
**Describe the bug**
Hi,
now the Readme in chapter "installation" is not actual. In this file there is information that configure.sh should be called after cloning "dev" branch, however there is no configure.sh in dev branch.

**Comment by dennisklein** [comment]
You can find the legacy FairSoft installation files in the subdirectory `legacy` from now on. So, after cloning FairSoft, execute `cd FairSoft/legacy` and then `./configure.sh` should work.

FairSoft is currently in the process of being migrated to the Spack package manager. Find instructions in the README of the FairSoft repo: https://github.com/FairRootGroup/FairSoft/blob/dev/README.md. Note that this is a development iteration and not the final version that is going to be released, quite some changes are to be expected still - anyhow if you are interested to beta-test you are welcome to try it and provide feedback.

**Comment by dennisklein** [comment]
Updated the README in `master` (2b8dcfe07e9160274c3e80c5e26cbc5386284e00) and `dev` (5db08328b65f54dcb4b98326a6848b9726ac65b3).
