### ISSUE TITLE
Issue with install due to failure to download cmake.

### ISSUE THREAD

**Issue by carlu** [FairRootGroup/FairRoot#1016]
**Describe the bug**
Following the instructions to download and compile FairRoot from the GitHub home page results in the error "--E-- Cannot unpack package cmake".

After some poking around I found that the file basics/cmake-3.17.3.tar.gz was actually a HTML document from "public.kitware.com" stating file not found (404 error). 

Clearly the download failed. I'm not sure whether this is a problem at my end or if the file has moved permanently but the initial error message wasn't too helpful so I thought I should report it once I figured out the problem.

**To Reproduce**
1. Run configure.sh to install FairRoot on system with missing or old version of cmake.
2. Download of cmake fails due to 404.
3. Build script tries to unpack 404 HTML document as if it were a tgz file.

**Expected behavior**
configure.sh script would download and install cmake as the version on my system was too old. 

**Logs / Screenshots**
Install log:
The build process for the external packages for the FairRoot Project was started at 231020_132347

Use these cached settings:   

compiler=gcc
debug=no
optimize=no
build_MQOnly=no
geant4_download_install_data_automatic=yes
geant4_install_data_from_dir=no
geant4mt=no
build_root6=yes
build_python=yes
install_sim=yes
SIMPATH_INSTALL=/filestore/programs/fair_install/FairSoftInst
platform=linux

Ok [Y/n]:
*** Compiling the external packages with the GCC compiler
*** Building the libraries with optimization
----------------- Install FairSoft ---------------
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- The Fortran compiler identification is GNU
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found GCC Version >= 4.8  
-- Found all necessary compilers.
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname 
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found 
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found all necessary X11 features.
-- Found OpenGL: /usr/lib64/libGL.so
-- Found all necessary OpenGL features.
-- Found CURL: /usr/lib64/libcurl.so (found version "7.29.0")
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k")
-- Found all necessary programs in PATH.
-- Performing Test HAS_CXX11 
-- Performing Test HAS_CXX11 - Success
-- Current compiler does suppport -std=c++11 option.
-- Performing Test HAS_LIBCXX
-- Performing Test HAS_LIBCXX - Failed
-- Current compiler does not suppport -stdlib=libc++
-- Found PythonInterp: /usr/bin/python (found version "2.7.5")
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5")
-- Found Subversion: /usr/bin/svn (found version "1.7.14")
-- Configuring done
-- Generating done
-- Build files have been written to: /filestore/programs/fair_install/FairSoft/legacy/test/build
The following parameters are set.
System              :  64bit 
C++ compiler        :  g++   
C compiler          :  gcc   
Fortran compiler    :  gfortran
CXXFLAGS            :  -O2 -std=c++11
CFLAGS              :  -O2   
FFLAGS              :  -O2   
CMAKE BUILD TYPE    :  Release
Compiler            :  gcc   
Fortran compiler    :  gfortran
Debug               :  no
Optimization        :  no
Platform            :  linux 
Architecture        :  linuxx8664gcc
G4System            :  Linux-g++
g4_data_files       :
g4_get_data         :
build G4 with MT    :  no
Number of parallel
processes for build :  40
Installation Directory:  /filestore/programs/fair_install/FairSoftInst
Found cmake version older than 3.16.0 in PATH
This version is to old
install cmake as external package
*** Unpacking cmake-3.17.3.tar.gz ..............
--E-- Cannot unpack package cmake

**System information (please complete the following information):**
 - OS: Centos7
 - Compiler: gcc 4.8.5
 - Environment: FairSoft cloned direct from GitHub today

**Comment by karabowi** [comment]
Dear Carl, 
if you need a quick solution to your problem and install FairSoft,
please edit your `scripts/package_versions.sh` file
and exchange the line:
`export CMAKE_LOCATION="http://www.cmake.org/files/v3.13/"`
with
`export CMAKE_LOCATION="http://www.cmake.org/files/v3.17/"`

**Comment by carlu** [comment]
Thanks for the extremely quick reply!
I actually managed to get it to compile using symlinks to the newer version of cmake, but your solution is much nicer so I will switch.

**Comment by dennisklein** [comment]
Fixed in FairRootGroup/FairSoft@941b225b02847c198858f8666875c2fb75242d2b.
