### ISSUE TITLE
2/55 post build tests failed.

### ISSUE THREAD

**Issue by carlu** [FairRootGroup/FairRoot#1026]
**Describe the bug**
At the end of the FairSoft/FairRoot build process I run "make test" and find that the following two tests fail:

34 - ex_MQ_pixel_simulation (Failed)
38 - pixelSplitDDS (Failed)

**To Reproduce**
Build FairSoft (jun19p1-504-gfc4e5f0) and FairRoot (v18.2.0-281-gbcf73f666) following instructions on FairRoot GitHub page. 

FairSoft Options: GCC, No debug symbols, build simulations, no python bindings.

After FairRoot is installed run "make test" in the build folder.

**Expected behavior**
All tests passed.

**System information (please complete the following information):**

I have tried this on two systems. Both are VirtualBox VMs running on a CENTOS7 x86_64 host system.

System 1:
 - OS: XUbuntu 2004
 - Compiler: GCC 9.3, cmake 3.16.3
 - Environment: FairSoft: jun19p1-504-gfc4e5f0, FairRoot: v18.2.0-281-gbcf73f666

System 2:
- OS: Fedora 33
 - Compiler: GCC 10.2., cmake 3.18.3
 - Environment: FairSoft: jun19p1-504-gfc4e5f0, FairRoot: v18.2.0-281-gbcf73f666

**Additional context**
On the Fedora system I ran into a problem when FairSoft was building flatbuffers (error: writing 1 byte into a region of size 0). This was with the compilation of the flatbuffer tests so I was able to get around it by disabling compilation of the tests. On the Ubuntu system this problem didn't occur.
The two failed tests are the same on both systems and they fail consistently.

**Comment by dennisklein** [comment]
Please attach the following logs:
* CMake configure log from FairRoot (printed on screen by the first `cmake` command issued)
* Test log file `Testing/Temporary/LastTest.log` from the build folder after running `make test`

Thx!

**Comment by carlu** [comment]
**Cmake output:**
[cmakelog.txt](https://github.com/FairRootGroup/FairRoot/files/5537940/cmakelog.txt)

**Test log:**
[LastTest.log](https://github.com/FairRootGroup/FairRoot/files/5537944/LastTest.log)

**Comment by dennisklein** [comment]
I believe the current `dev` branch of FairRoot fixes the issue that made them fail consistently. However, pls note that the tests are still failing occasionally for other reasons. Thank you for your bug report!
