### ISSUE TITLE
Checksum mismatch when reading old data

### ISSUE THREAD

**Issue by fuhlig1** [FairRootGroup/FairRoot#1030]
The following problem was reported by Thomas per mail.

> Hi,
> We have an issue with reading back our old data, previously produced with an older version of FairRoot. See below. It can be fixed by increasing the class version for a few FairRoot classes, like FairMCPoint, FairEventHeader. Of course we can do it on our side having our own version of FairRoot, but would be good if it is fixed upstream.
>  
> Cheers,
> Thomas
>  
>  
>  
> TStreamerInfo::BuildCheck:0: RuntimeWarning:
>    The StreamerInfo for version 5 of class FairMCPoint read from the file root://eospublic.cern.ch//eos/experiment/ship/data/Mbias/background-prod-2018/pythia8_Geant4_10.0_withCharmandBeauty63000_mu.root
>    has a different checksum than the previously loaded StreamerInfo.
>    Reading objects of type FairMCPoint from the file root://eospublic.cern.ch//eos/experiment/ship/data/Mbias/background-prod-2018/pythia8_Geant4_10.0_withCharmandBeauty63000_mu.root
>    (and potentially other files) might not work correctly.
>    Most likely the version number of the class was not properly
>    updated [See ClassDef(FairMCPoint,5)].

The now used FairRoot version is v18.4.2, Thomas will check for information about versions an environment at production time of the files.

**Comment by fuhlig1** [comment]
@ThomasRuf, Try to add you as participant.

**Comment by ThomasRuf** [comment]
I am not sure what more information I can give. At production time, we had  ClassDef(FairMCEventHeader,2); and  ClassDef(FairMCPoint,5); the same as now in the FairRoot git repository. This worked without problems until we changed to a more recent ROOT version, v6-22-02, which is more picky.

**Comment by karabowi** [comment]
Is it still a valid issue?

I tried to recreate the problem with the oldest file I found, but to no avail.

```
karabowi@citmac007:~/panda/pandaroot/dev/build $ root -l /Volumes/RK_MOVED/pandaroot/PandaRoot/macro/gem/Gem_3Stations_211_3part_n100.root
root [0] 
Attaching file /Volumes/RK_MOVED/pandaroot/PandaRoot/macro/gem/Gem_3Stations_211_3part_n100.root as _file0...
(TFile *) 0x7fb894f43cd0
root [1] _file0->GetVersion()
(int) 61008
```

**Comment by olantwin** [comment]
Hi @karabowi , thanks for following up on this.

Reading the file that originally triggered the issue, I can not reproduce the issue using:

FAIRROOT_VERSION=v18.4.2_snd (contains to additional commits which don't touch the ClassDef)
ROOT_VERSION=v6-26-02

Both opening the file and reading a few different branches does not trigger any RuntimeWarning.

So unless there are additional steps necessary to reproduce the issue, it seems that the problem has disappeared.

**Comment by karabowi** [comment]
Great. Should the problem reappear, we can reopen the issue.
