### ISSUE TITLE
FindFairRoot.cmake does not find FairRoot due to lib64 folder

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#1036]
**Describe the bug**
The FindFairRoot.cmake module searches for `libBase.so/.dylib` in `${FAIRROOTPATH}/lib` but the build process on openSuse15.2 puts them into the `${FAIRROOTPATH}/lib64`folder using the spack installation. Therefore the insallation of PandaRoot fails.

A fix would be easy by extending the module to also search in lib64.

**Comment by dennisklein** [comment]
> A fix would be easy by extending the module to also search in lib64.

We would accept such a fix. To which versions of FairRoot would you need it backported? Just 18.4? If you propose the fix in the next days, it will be naturally included in the upcoming 18.6 release.

**Comment by TobiasStockmanns** [comment]
A backport to 18.4 would be sufficient.

**Comment by dennisklein** [comment]
Thank you for the fix! I have backported the commit to the `v18.4_patches` branch, a patch release will follow in a few days.
