### ISSUE TITLE
Default Installation is dev. 

### ISSUE THREAD

**Issue by ngeraks** [FairRootGroup/FairRoot#1070]
Dear FairRoot developers,
1. The default installation instructions git clone the dev branch.
IMHO it should be master or latest stable release.

2. When using the FindROOT.cmake file I get this error
CMake Error at FairRoot/install/share/fairbase/cmake/modules/FindROOT.cmake:84 (Math):
  Math cannot parse the expression: "*10000 + *100 + ": syntax error,
  unexpected exp_TIMES (1).
  It seems the variables ROOT_FIND_VERSION_MAJOR/MINOR/PATCH are missing at line 84.
  Commenting resumes cmake configuration normally.

3. The dev branch has removed the FindROOT.cmake on which the templates still depend. (also experiments based on FairRoot)
I suggest either keeping it, or providing templates with the new cmake-root-target-thing.

P.S.
I just realized what I mentioned is actually the last point left in: Modernize CMake phase 2 #933

**Comment by dennisklein** [comment]
> The default installation instructions git clone the dev branch.
> IMHO it should be master or latest stable release.

Absolutely agreed.

> 2. When using the FindROOT.cmake file I get this error
> CMake Error at FairRoot/install/share/fairbase/cmake/modules/FindROOT.cmake:84 (Math):
> Math cannot parse the expression: "*10000 + *100 + ": syntax error,
> unexpected exp_TIMES (1).
> It seems the variables ROOT_FIND_VERSION_MAJOR/MINOR/PATCH are missing at line 84.
> Commenting resumes cmake configuration normally.
> 
> The dev branch has removed the FindROOT.cmake on which the templates still depend. (also experiments based on FairRoot)
> I suggest either keeping it, or providing templates with the new cmake-root-target-thing.

The project template in the `dev` branch should actually work with a FairRoot `dev`. Nevertheless, you are hitting an unusual situation these days, the `dev` branch already contains major breaking changes (see also the work-in-progress https://github.com/FairRootGroup/FairRoot/blob/dev/CHANGELOG.md) as it prepares the upcoming FairRoot 19.0 release (which will have exactly the same features as 18.6 in the C++ APIs, but the CMake will not be compatible any more).
