### ISSUE TITLE
Problems with links (FairRootManager, FairRunAnaProof)

### ISSUE THREAD

**Issue by ngeraks** [FairRootGroup/FairRoot#1075]
While browsing our MpdRoot gitlab repository I noticed a complaint of memory leaks from years ago. I have personally had this issue, so I began testing in order to solve it. 
The relatively old versions of FairSoft/Root (v18.2_patches)  is default for now for us but that is supposedly soon to change . For about a week of diagnosis we simplified our reconstruction chain to only include a single HitProducer by a suggestion from our tracking expert.  
This HitProducer ... produces hits and then links them. 
  It uses the TClonesArray new placement and Delete to free them. 
 (I tested ConstructedAt with a custom Clear for the hits - It did not help for memory, somewhat improved time)
   
I experimented with 500 pions/event, 1000 events produced 1.7 GiB with fRun->SetUseFairLinks(true);   
Setting fRun->SetUseFairLinks(false) results in 321 MiB. Commenting the links in the producer - the same.  
If we make this a bit more extreme 10k events costed 14 GiB with UseFairLinks and 321 without.   
  
Then I tried to run in proof-mode (using FairRunAnaProof), that was running, however it did not produce any links. Memory was low, and since there are no Links there are no leaks.   
  
We suspected first our code. Tried all types of Delete(), Clear("C") with a MpdTpcHit::Clear which resets links, then  we moved to virtual destructors on everything FairMultiLinkedData /_interface, FairHit - Nothing...

So then I saw there was a bug there, which was supposedly fixed in FairRoot v18.4 - no dice.  
Installed FairSoft apr21 and one  of latest FairRoot devs/master (not sure) - same issue.
  
I forgot to mention during this process I ran various profiling tools.
 Valgrind's memcheck, callgrind, but massif was the most useful in this case.  
![image](https://user-images.githubusercontent.com/78253750/124880396-ebfaa700-dfd6-11eb-9310-bc94aa0edb9d.png)
  
Finally, after a week of poking at this, commenting this ```    fReqBrNames.emplace_back(BrName);``` at line 523 in FairRootManager::GetObject  seems to fix it.  This is getting called from FairMultiLinkedData::InsertHistory. 
In this context I am not sure what it is doing, I mean why do we save the branch name? Why doesn't this list get cleared?   
Anyway. Recompile. Code is purring. Does not pass 300 MiB. When I include our FillDstTask rises to 577 MiB due to loading other branches, but that is it.

Still, FairRunAnaProof does not have links, and since our code depends on them it is not possible to use it. GNU/parallel is the alternative of my choice.
Also, FairRunAnaProof does not merge the resulting worker files at the end. It produces a single empty file.

Cheers!

Edit:
Forgot to mention that these are the ways we do linking:
```pHit->AddLink(FairLink(MpdTpcHit::PointIndex, pointIndx));  ```
```pHit->AddLink(FairLink(MpdTpcHit::MCTrackIndex, trackIndx));```
Trying the long-style (with branch name) did not seem to fix it for me, maybe I did not try properly.

**Comment by dennisklein** [comment]
It appears the `fReqBrNames` vector was introduced in fdffd5782d1bfd0696506d7b73ccfba655c8519b. @sawenzel Can you comment on the excessive growth of this vector op is seeing?

**Comment by sawenzel** [comment]
This was done quite long ago... It appears to me that the `emplace_back` should only happen once for every unique BrName as the purpose of this vector is to keep track of what branches have been accessed at all. Maybe it's better to change it to a hash map or one needs to do a quick search before adding stuff to it.

**Comment by dennisklein** [comment]
@sawenzel @MohammadAlTurany Are you aware of any usage of this branch request monitor feature? I searched the AliceO2Group github organization and the FairRoot codebase and did not find any calls to `FairRootManager::GetReqBranchNames()`. If not and if you do not need it any I propose to just remove it, or at least make it opt-in only. What do you think?

**Comment by sawenzel** [comment]
Removing it would be ok for me.

**Comment by TobiasStockmanns** [comment]
In PandaRoot GetReqBranchNames() is not used. Also for the FairLinks and for InsertHistory I do not see a problem.

**Comment by dennisklein** [comment]
Thanks to everybody who has contributed to the resolution of this issue and especially @ngeraks for your time-consuming debugging! This is very much appreciated!
