### ISSUE TITLE
Feature request: allow for external RTDB backends

### ISSUE THREAD

**Issue by patternoia** [FairRootGroup/FairRoot#1079]
**Is your feature request related to a problem? Please describe.**
Hello,

as discussed on Monday's at FairRoot group meeting I am putting up this issue to track the proposed change to FairRoot.

In CbmRoot we implemented a TGenBase RTDB backend, but in order for it to work as expected, FairRoot shall be patched, additional clauses in the switch statement shall be added, etc. (see the presentation) Because of this patch TGenBase becomes a hard dependency of FairRoot which should not be the case.

**Describe the solution you'd like**
I propose to retouch the RTDB code to clearly define the RTDB's `ParIo` API so that any class implementing this API shall be recognized by the FairRoot properly.

**Additional context**
See [my solution](https://git.cbm.gsi.de/TGenBase/FairRoot/-/commit/251d0734e46420f621a07b023bddff27d7d56ceb?view=inline) in our gitlab.

Thanks for consideration.
Evgeny.

**Comment by dennisklein** [comment]
After having reviewed the affected code, I have to reclassify this as a bug report. 08609c153e4aeaedce4d3367506721d2c3db1f6b introduced a regression by closing down the set of `FairParIo`s. What you are asking here has already been a feature 9 years ago AFAICS ;)
