### ISSUE TITLE
Cleanup/Repair `test/`

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#1087]
Many FairLogger tests appear broken. @fuhlig1 @rbx Are they still needed?

**Comment by rbx** [comment]
Since FairRoot/FairLogger is mostly just a wrapper around FairLogger, which has its own tests, I would say the tests here are not needed.

**Comment by dennisklein** [comment]
> Since FairRoot/FairLogger is mostly just a wrapper around FairLogger, which has its own tests, I would say the tests here are not needed.

Is the `::FairLogger` wrapper doing anything that has been tested?
* Can you check the existing tests and make sure there is nothing any more that?
* Can you check what is the reason why the existing tests fail? Was there a breaking change?

**Comment by dennisklein** [comment]
@rbx @fuhlig1 I guess, if you both agree to delete those tests and not bother sorting this out in detail, then I am fine with it, too. But let's stop carrying them around in a broken state.

**Comment by fuhlig1** [comment]
If I am correct the old FairLogger isn't used anymore. Also for CbmRoot we moved to the external fairlogger project without the FairRoot wrapper. So from my side the tests can be removed.

Maybe we should put together some description how to move from FairLogger.h to Logger.h such that we can deprecate FairLogger.h in future. What do you think?

**Comment by rbx** [comment]
> Maybe we should put together some description how to move from FairLogger.h to Logger.h such that we can deprecate FairLogger.h in future. What do you think?

Sure, I can collect and document all that is necessary for such a switch. One of the things that goes away without the wrapper is this:
https://github.com/FairRootGroup/FairRoot/blob/master/fairtools/FairLogger.cxx#L36-L46
The additional Fatal handler only exists if the FairRoot/FairLogger is instantiated, either by calling `GetLogger` or `gLogger`.
How did you solve this in CbmRoot?
Actually, I would love to get rid of this feature entirely, by removing even the `fair::Logger::OnFatal()` method.
