### ISSUE TITLE
Strange geometry file format for CAVE 

### ISSUE THREAD

**Issue by kurbatov-lang** [FairRootGroup/FairRoot#1137]
Because CAVE is  a mother volume for all geometries, you should specify only dimensions in 3D space as was earlier in  Geant3.
Currently it is defined for BOX by coordinates of 8 corner points( see macro run_tutorial1.C; geometry file for CAVE is
cave_vacuum.geo).Immediately one should ask - COORDINATES IN WHAT COORDINATE SYSTEM? In HOW TO
section of https://fairroot.gsi.de I did not find the answer to such a question.

I think it is better if for mother volume we specified only dimensions in 3D space!

**Comment by MohammadAlTurany** [comment]
The origin is 0,0,0 and the eight corners define your cave. All other volumes are set relative to the mother volume (see https://fairroot.gsi.de/index.html%3Fq=node%252F32.html)

**Comment by kurbatov-lang** [comment]
Dear Mohammad!

Still for me it is unclear. If you specify corner coordinates(for BOX)

then immediatey you should say which coordinate system you are using for 
them.

What is coordinate system for such a case?

Thank you Vladimir

**Comment by MohammadAlTurany** [comment]
What day you mean by coordinate system? 
it is a Cartesian coordinate system with 0,0,0 as origin. The eight corners are relative to 0,0,0.
maybe this link is helpful:  https://fairroot.gsi.de/index.html%3Fq=node%252F33.html

**Comment by dennisklein** [comment]
Reopen, if anything is still unclear.
