### ISSUE TITLE
fatal error: 'TMCProcess.h' file not found, when installing the template

### ISSUE THREAD

**Issue by huagenxu** [FairRootGroup/FairRoot#1141]
**Describe the bug**
After having installed fairsoft_apr21 and FairRoot_v18.6.7 on Ubuntu 20.04.3 LTS, the error occurred while installing the templates by following the instruction "step by step installation". It seems that the VMC header files were not found/included by CMake scripts.

**To Reproduce**
1. Describe environment: The SIMPATH as well as the FAIRROOTPATH are correctly exported. 
2. Describe compile options used:  cmake ../MyTest
3. Give commands you invoked: cmake 

**Expected behavior**
The missing header file, e.g., TMCProcess.h, should be included by the CMake scripts since ROOT header file folder is just in parallel with VMC. The ROOT works properly.

**Logs / Screenshots**

In file included from /home/huagen/workspace/MyTest/KoaData/KoaStack.h:35:
/home/huagen/workspace/FairRoot_v18.6.7/install/include/FairGenericStack.h:23:10: fatal error: 'TMCProcess.h' file not found
#include <TMCProcess.h>        // for TMCProcess

**System information (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS (same with MacOS 11.6.1)
 - Compiler: GCC 9.3
 - Environment: FairSoft apr21, FairRoot v18.6.7

See [github markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) on how to format inline codes examples and logs.

**Comment by dennisklein** [comment]
This problem is fixed in the `dev` branch. However, it has not been backported to the `v18.6_patches` branch yet (which we should do now).

**Comment by dennisklein** [comment]
d31ebb0a7301b63455d31d63554283282ee343bc scheduled for release in v18.8.
