### ISSUE TITLE
Please Port pixelDetector examples to Geant4

### ISSUE THREAD

**Issue by ChristianTackeGSI** [FairRootGroup/FairRoot#1148]
**Is your feature request related to a problem? Please describe.**
examples/MQ/pixeldetector is currently only available in a Geant3 version.
#995 and #1147 will disable most of pixelDetector currently.

**Describe the solution you'd like**
Please change pixelDetector to be runnable with Geant4 as well.

**Describe alternatives you've considered**
Keeping this test as a "old style" thing.

**Additional context**
See: #995
See: #1147

**Comment by dennisklein** [comment]
#1149, #1159 scheduled for release in v18.8.
