### ISSUE TITLE
Handling Of Interruptions in FairRunAna

### ISSUE THREAD

**Issue by kurbatov-lang** [FairRootGroup/FairRoot#1175]
Dear colleagues. I have a question, not comment: In FairRunAna.cxx(in FairRunAna::Run(..)) there is piece of code:
      gSystem->IgnoreInterrupt();
      //  gFRAIsInterrupted = kFALSE;
      signal(SIGINT, FRA_handler_ctrlc);

      if ( gFRAIsInterrupted ) {
        LOG(warn) << "FairRunAna::Run() Event loop was interrupted by the user!";
        break;
      }
As I understand gSystem->IgnoreInterrupt(); switches off all interruptions, including Ctrl/C, but following statements do analysis of interruption.Why?

**Comment by dennisklein** [comment]
Reopen, if anything is still unclear.
