### ISSUE TITLE
Add virtual finalize method for FairGenerator.

### ISSUE THREAD

**Issue by mgoncerz** [FairRootGroup/FairRoot#1184]
For my use case, I have interfaced external Monte Carlo generators to our FairRoot-based software. Many of them provide additional information when finalizing. 

While it's very easy to implement it manually and call it from a macro, it would be convenient to have a virtual Finalize method in the base FairGenerator class, that would be always called somewhere at the end of the production run.

**Comment by karabowi** [comment]
After short discussion I think we can add the virtual Finish() to FairGenerator. 
It is quite interesting, that this feature was not requested by anyone for almost 20 years.
