### ISSUE TITLE
Missing check_system.csh

### ISSUE THREAD

**Issue by jdfrankland** [FairRootGroup/FairRoot#119]
I have just installed the latest versions of FairSoft/FairRoot from the git repositories, on a Ubuntu 14.10 box. My shell is csh.
When I do
$ source [path_to_installation]/bin/FairRootConfig.csh
to setup FairRoot, I get the following error:
[path_to_installation]/bin/check_system.csh: No such file or directory.
In fact, check_system.sh is there, it looks as though check_system.csh was forgotten in the installation step.
Cheers

**Comment by MohammadAlTurany** [comment]
Dear John,

Thanks for reporting this issue, it is now solved in dev.

Best regards,

Mohammad
