### ISSUE TITLE
Create a reset method for class FairRun

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairRoot#1219]
**Motivation:**
In the current algorithm, the base singleton class FairRun cannot be reinstantiated for another purpose. For example, if we want to have a program to run the simulation using FairSimRun and then once it's finished, run an analysis using FairAnaRun. This is impossible because FairAnaRun cannot be instantiated since its base class FairRun has been already instantiated when running FairSimRun. Even if we delete FairRunSim in the end of simulation, we would still have segmentation violation because FairRun class simply cannot be reinstantiated.

**Describe the solution you'd like**
Add an `ResetInstance()` method inside the class, like:
```cpp
void static FairRun::ResetInstance()
{
        fInstance = 0;
} 
```
If this is implemented, following code would work:
```cpp
auto sim = new FairSimRun();
// simulation starts
....
// simulation ends
delete sim;
FairRun::ResetInstance();

// analysis begins:
auto ana = new FairAnaRun
```

It could also be done by reseting instance of FairRun in its deconstructor:
```cpp
FairRun::~FairRun()
{
    LOG(debug) << "Enter Destructor of FairRun";
    delete fTask;   // There is another tasklist in MCApplication,
    // but this should be independent
    delete fRtdb;   // who is responsible for the RuntimeDataBase
    delete fEvtHeader;
    fInstance = 0; // reset the pointer to 0;
    LOG(debug) << "Leave Destructor of FairRun";
}

```

**Comment by fuhlig1** [comment]
Could you please explain your use case. Why do you need to reuse the same ROOT session for a simulation and afterwards for a analysis?

**Comment by YanzhaoW** [comment]
> Could you please explain your use case. Why do you need to reuse the same ROOT session for a simulation and afterwards for a analysis?

@fuhlig1 Yes. My use case includes both simulation and analysis processes. The compiled c++ executable is intended to perform the simulation first (which utilises FairSimRun) and then use the result to perform an analysis with multiple FairTasks (using FairAnaRun). Without reseting the instance pointer to 0 i FairRun, I cannot instantiate FairAnaRum after FairSimRun in a single executable program.

**Comment by karabowi** [comment]
Hi Yanzhao, I do not anticipate to have such a feature in FairRoot anytime soon.
As a quick solution, maybe you can use threads to run simulation and reconstruction in one program?

I have created a simple macro in fairroot/examples/advanced/Tutorial3/macro/run_thread.C:

```
#include <thread>

#include "TROOT.h"

void runSim() {
    gROOT->Macro("run_sim.C");
}

void runDigi() {
    gROOT->Macro("run_digi.C");
}

int run_thread() {
    std::thread threadSim(runSim);
    threadSim.join();

    std::thread threadDigi(runDigi);
    threadDigi.join();

    return 0;
}

int main() {
    run_thread();
    return 0;
}
```

You can either run with: `root -l -q run_thread.C`,
or via an executable with: 

```
g++ run_thread.C -o run_thread_exe `root-config --cflags --glibs`
./run_thread_exe
```

Hope that example will help you to run your program.

**Comment by fuhlig1** [comment]
> Yes. My use case includes both simulation and analysis processes. The compiled c++ executable is intended to perform the simulation first (which utilises FairSimRun) and then use the result to perform an analysis with multiple FairTasks (using FairAnaRun). Without reseting the instance pointer to 0 in FairRun, I cannot instantiate FairAnaRum after FairSimRun in a single executable program.

Is there any reason why you can't run first execute a simulation and after that has finished run a reconstruction?

There is also another possibility to run a simulation and reconstruction I one executable. You can add the tasks you want to execute to the task list of the FairRunSim. In that case first the simulation and right after the analysis will be executed event by event.

**Comment by YanzhaoW** [comment]
> > Yes. My use case includes both simulation and analysis processes. The compiled c++ executable is intended to perform the simulation first (which utilises FairSimRun) and then use the result to perform an analysis with multiple FairTasks (using FairAnaRun). Without reseting the instance pointer to 0 in FairRun, I cannot instantiate FairAnaRum after FairSimRun in a single executable program.
> 
> Is there any reason why you can't run first execute a simulation and after that has finished run a reconstruction?
> 
> There is also another possibility to run a simulation and reconstruction I one executable. You can add the tasks you want to execute to the task list of the FairRunSim. In that case first the simulation and right after the analysis will be executed event by event.

Thanks for the reply. If I'm not wrong and if I understand you correctly, I don't think FairSimRun can run any tasks. I checked that in the method `FairRunSim::Init()`, there is no such provocation as in `FairRunAna`:
https://github.com/FairRootGroup/FairRoot/blob/a3f91e09509988ca1d8532e712d246df0c4d4887/base/steer/FairRunAna.cxx#L376

Neither is there the provocation of ExecuteTask method in `FairRunSim` as in `FairRunAna`:
https://github.com/FairRootGroup/FairRoot/blob/a3f91e09509988ca1d8532e712d246df0c4d4887/base/steer/FairRunAna.cxx#L466-L480

**Comment by YanzhaoW** [comment]
> Hi Yanzhao, I do not anticipate to have such a feature in FairRoot anytime soon. As a quick solution, maybe you can use threads to run simulation and reconstruction in one program?
> 
> I have created a simple macro in fairroot/examples/advanced/Tutorial3/macro/run_thread.C:
> 
> ```
> #include <thread>
> 
> #include "TROOT.h"
> 
> void runSim() {
>     gROOT->Macro("run_sim.C");
> }
> 
> void runDigi() {
>     gROOT->Macro("run_digi.C");
> }
> 
> int run_thread() {
>     std::thread threadSim(runSim);
>     threadSim.join();
> 
>     std::thread threadDigi(runDigi);
>     threadDigi.join();
> 
>     return 0;
> }
> 
> int main() {
>     run_thread();
>     return 0;
> }
> ```
> 
> You can either run with: `root -l -q run_thread.C`, or via an executable with:
> 
> ```
> g++ run_thread.C -o run_thread_exe `root-config --cflags --glibs`
> ./run_thread_exe
> ```
> 
> Hope that example will help you to run your program.

Thanks for the reply. I'm not very familiar with gRoot->Macro() function. Does it mean the algorithm just opens another process for interpreting the macro file using ROOTCint?

**Comment by fuhlig1** [comment]
> > > Yes. My use case includes both simulation and analysis processes. The compiled c++ executable is intended to perform the simulation first (which utilises FairSimRun) and then use the result to perform an analysis with multiple FairTasks (using FairAnaRun). Without reseting the instance pointer to 0 in FairRun, I cannot instantiate FairAnaRum after FairSimRun in a single executable program.
> > 
> > 
> > Is there any reason why you can't run first execute a simulation and after that has finished run a reconstruction?
> > There is also another possibility to run a simulation and reconstruction I one executable. You can add the tasks you want to execute to the task list of the FairRunSim. In that case first the simulation and right after the analysis will be executed event by event.
> 
> Thanks for the reply. If I'm not wrong and if I understand you correctly, I don't think FairSimRun can run any tasks. I checked that in the method `FairRunSim::Init()`, there is no such provocation as in `FairRunAna`:
> 
> https://github.com/FairRootGroup/FairRoot/blob/a3f91e09509988ca1d8532e712d246df0c4d4887/base/steer/FairRunAna.cxx#L376
> 
> Neither is there the provocation of ExecuteTask method in `FairRunSim` as in `FairRunAna`:
> 
> https://github.com/FairRootGroup/FairRoot/blob/a3f91e09509988ca1d8532e712d246df0c4d4887/base/steer/FairRunAna.cxx#L466-L480

There is the following line in FairRunSim

https://github.com/FairRootGroup/FairRoot/blob/a3f91e09509988ca1d8532e712d246df0c4d4887/base/steer/FairRunSim.cxx#L174

which add the task list to the MC Application which steers the state machine of the simulation. In the FinishEvent() function after all the transport took place the defined FairTasks are executed

https://github.com/FairRootGroup/FairRoot/blob/a3f91e09509988ca1d8532e712d246df0c4d4887/base/sim/FairMCApplication.cxx#L816

Also all other needed functions of FairTask are called at the correct places.

**Comment by YanzhaoW** [comment]
@fuhlig1  I see. Thanks for the help.

**Comment by fuhlig1** [comment]
@YanzhaoW,

could you please try if the proposed solution works for you and report back.

**Comment by YanzhaoW** [comment]
@fuhlig1 Yes, I can confirm this works. But many existing tasks are already embedded with `FairRunAna` and thus cannot be run with `FairRunSim`, such as:

https://github.com/R3BRootGroup/R3BRoot/blob/4e2decfab13d80ee412c6dfeabfcc19c4efd4976/neuland/digitizing/R3BNeulandDigitizer.cxx#L45-L51

But with my own defined tasks, it's not a problem.
