### ISSUE TITLE
On the two meanings of ROOT_GENERATE_DICTIONARY

### ISSUE THREAD

**Issue by klenze** [FairRootGroup/FairRoot#1221]
There are two different cmake things called ROOT_GENERATE_LIBRARY:
[The Root one](https://github.com/root-project/root/blob/master/cmake/modules/RootMacros.cmake#L270) and [the FairRoot](https://github.com/FairRootGroup/FairRoot/blob/dev/cmake/modules/ROOTMacros.cmake#L46) one. 

The former gets included by calling find_package2(...ROOT...), the latter get included explicitly. If a user includes ROOTMacros before they do the find_package2(...ROOT...), the user will get an error that ROOT_GENERATE_LIBRARY is called with the wrong number of arguments. (May Cthulhu help a user who misspells ROOTMacros as RootMacros and gets only the version from Root altogether.)

I think it would be a great idea if FairRoot acquired their own prefix for their cmake macros/functions instead of sharing them with ROOT. From my understanding, the there is not really a CMake prefix assignment authority -- one can simply grab whatever prefix one likes. Using FAIRROOT_ as a prefix will make collisions with other projects less likely.

**Comment by dennisklein** [comment]
Yes, that is a good idea, which we already adopted, check [`fairroot_target_root_dictionary()`](https://github.com/FairRootGroup/FairRoot/blob/dev/cmake/modules/FairRootTargetRootDictionary.cmake#L13).

**Comment by ChristianTackeGSI** [comment]
I assume you meant ROOT_GENERATE_DICTIONARY and not …LIBRARY as used before in the title of this issue?

That said, I have created #1328 to rename our `ROOT_GENERATE_DICTIONARY` to `FAIRROOT_GENERATE_DICTIONARY` for FairRoot 19.0 which targets a lot of breaking CMake changes anyway.

**Comment by klenze** [comment]
> I assume you meant ROOT_GENERATE_DICTIONARY and not …LIBRARY as used before in the title of this issue?

Yes, exactly. This should fix things. Please close this issue when your PR gets merged. 

Thanks,
   Philipp

**Comment by ChristianTackeGSI** [comment]
#1328 was merged. It's not yet in any release.

Closing as allowed by @klenze.
