### ISSUE TITLE
Provide a way to compile FairRoot without Proof support

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#1229]
ALICE is currently having big issues due to the number of libraries we link against even for the simplest workflow. One of the top offender is actually libBase, due to the fact it links by default packages like boost_iostream and Proof which are in general not needed and in particular will not be used at all by us.
While we are trying to minimise the dependencies on our side and link libBase only where it's actually needed, we do use some of its core functionalities so the problem can only be fixed in FairRoot itself. Would that be possible?

**Comment by dennisklein** [comment]
relates to #1228

**Comment by ChristianTackeGSI** [comment]
See also #1235

**Comment by ChristianTackeGSI** [comment]
#1235 has been merged to `dev`. I think, this should fix this issue at least for dev?

Should we backport the first commit in that PR to 18.x?

What else is needed to address this?

**Comment by dennisklein** [comment]
024660d433efed30d73141ffacc9db2c846452d4 scheduled for release in v18.8. (Disable Proof via `-DBUILD_PROOF_SUPPORT=OFF`)
