### ISSUE TITLE
BranchList incomplete

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#124]
After the change of the FairRootManager the BranchList only contains the branch names of the branches registered in this run (e.g. all digi branches) but not any longer the branch names of the input file (e.g. sim branches).
This causes massive problems with the usage of FairLinks because the method FairRootManager::GetBranchId(BranchName) returns in most cases -1 which breaks the links.

**Comment by MohammadAlTurany** [comment]
Problem solved in DEV 

https://github.com/FairRootGroup/FairRoot/pull/125
