### ISSUE TITLE
Ownership transferring needs to be explicitly expressed

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairRoot#1242]
As C++ Core guidelines (I.11) suggests:
> Never transfer ownership by a raw pointer (T*) or reference

## Problem:
For example, the event header, which is denoted as `fEvtHeader`, is owned by class `FairRun` as it's deleted in the deconstructor.

But at the same time, there is a method, which can reseat the fEvtHeader pointer to another user-defined object:
https://github.com/FairRootGroup/FairRoot/blob/8501262650150c547e4aa6dbaff204e476ab6e41/base/steer/FairRun.h#L79

Here we have two problems: 
1. If fEvtheader is already pointing to an existing event header, that existing one won't get deleted in the end and hence we have a memory leak.
2. Users have absolutely no idea whether they need to delete the pointer they passed to the method or not. If they don't go deep into the source files, the default is to delete the pointer because it's passed as a raw pointer.

## Suggestions:
1. Whenever a class owns an object, encapsulate the pointer into `std::unique_ptr<>`. ( this also increases exception safety. )
2. When a class need to consume an object, make the parameter as the type `std::unique_ptr<>`
    As in the case of the example, following code is much better:
    ```cpp
    void SetEventHeader(std::unique_ptr<FairEventHeader> NewEvHeader) 
    { 
        fEvtHeader = std::move(NewEvHeader); // reseating the unique_ptr
    }
    ```

    With this, the two problem mentioned above are solved. First, old event header get deleted automatically. Second, User knows this is an ownership transferring and he doesn't need to delete the pointer created by him.

    For the user, all he needs to do is:
    ```cpp
    auto eventHeader = std::unique_ptr<R3BEventHeader>(new R3BEventHeader());
    FairRun::Instance()->SetEventHeader(std::move(eventHeader));    // ownership transferring.
    ```

**Comment by dennisklein** [comment]
:+1: Yes, ownership documentation is extremely poor in FairRoot. Contributions welcome! Related #923.

**Comment by dennisklein** [comment]
Note: In general, the topic is not trivial, some facilities in FairRoot are based on ROOT facilities which *may* be actually take care about ownership in a non-obvious way... you may find those links interesting to read: https://root.cern/manual/object_ownership/, https://lbianch.github.io/programming/2016/12/19/root-histograms-uniqueptr.html

**Comment by YanzhaoW** [comment]
> 👍 Yes, ownership documentation is extremely poor in FairRoot. Contributions welcome! Related #923.

Sure, I will make a pull request for the `SetEventHeader`.

**Comment by YanzhaoW** [comment]
> Note: In general, the topic is not trivial, some facilities in FairRoot are based on ROOT facilities which _may_ actually take care about ownership in a non-obvious way... you may find those links interesting to read:
> 
> * https://root.cern/manual/object_ownership/
> * https://lbianch.github.io/programming/2016/12/19/root-histograms-uniqueptr.html

Thanks for the info. This is another example how ROOT tries to be like those high level languages such as python (dynamic typing, garbage collector..) and, at the same time, requires the speed and efficiency in C/C++.

What I would recommend is there should be no deletions in the deconstructor of FairRoot classes. Let smart pointers delete them automatically and follow the guidelines:
>Never transfer ownership by a raw pointer (T*) or reference

For those objects such as `TH1`, whose ownership is dealt with by ROOT, we could only count on the awareness of FairRoot users.

**Comment by dennisklein** [comment]
> > 👍 Yes, ownership documentation is extremely poor in FairRoot. Contributions welcome! Related #923.
> 
> Sure, I will make a pull request for the `SetEventHeader`.

Some suggestions:
* Do not yet remove the old `SetEventHeader(FairEventHeader*)` in your PR, but mark it [`[[deprecated("Use SetEventHeader(std::unique_ptr<FairEventHeader>) instead")]]`](https://en.cppreference.com/w/cpp/language/attributes/deprecated) and add a comment that it takes ownership of the passed argument.
* Add the `SetEventHeader(std::unique_ptr<FairEventHeader>)` as a new overload.
* Deprecate the `FairRun::fEvtHeader` member variable with `[[deprecated("No replacement, will become private")]]` as well.

In a second step with a future major release we can then change the type of the member variable `FairRun::fEvtHeader` to `std::unique_ptr<FairEventHeader>` and make it `private`. With that release we will then delete the raw pointer overload of `SetEventHeader()` as well.

**Comment by dennisklein** [comment]
https://github.com/FairRootGroup/FairRoot/blob/18b71c213423ba2f4a6082e3c69c570cedcb4f51/base/event/FairEventHeader.cxx#L26-L29

calls eventually (in case of a `FairRootFileSink`):

https://github.com/FairRootGroup/FairRoot/blob/18b71c213423ba2f4a6082e3c69c570cedcb4f51/base/sink/FairRootFileSink.cxx#L235-L247

I look at this for 15 minutes already and still don't understand what the ownership semantics are 😞 ROOT...

I fear the event header becomes owned once someone calls its `FairEventHeader::Register` member function?!
