### ISSUE TITLE
FindROOT doesn't handle no version in v18.x

### ISSUE THREAD

**Issue by ChristianTackeGSI** [FairRootGroup/FairRoot#1256]
**Describe the bug**
Using the FindROOT in v18.x and calling

```cmake
find_package(ROOT REQUIRED)
```

without a `VERSION` gives an error.

**To Reproduce**
See above.

**Expected behavior**
Should just work

**Additional context**
We have a patch prepared for 18.8, we need to backport it.

**Comment by dennisklein** [comment]
fixed by cbfddda84031e8794155320319cf93b2abe4ca42

**Comment by dennisklein** [comment]
ah, needs backport to v18.6 and v18.4 still
