### ISSUE TITLE
Deprecate FairRoot::DataMatch?

### ISSUE THREAD

**Issue by ChristianTackeGSI** [FairRootGroup/FairRoot#1270]
@fuhlig1 suggests [here](https://github.com/FairRootGroup/FairRoot/pull/1269#pullrequestreview-1180568622) to deprecate FairRoot::DataMatch.

**Comment by fuhlig1** [comment]
Here the answer of Tobias, so we can deprecate FairRoot::DataMatch

> Hallo Florian,
> 
> die Library DataMatch kann auslaufen. Wir benutzen es nicht mehr in PandaRoot (weder über FairRoot noch über PandaRoot), da es zu langsam war.
> 
> LG,
> 
> Tobias
>

**Comment by ChristianTackeGSI** [comment]
@fuhlig1 would you mind writing an appropriate ChangeLog-Entry for 18.8?

For 19 (dev) we might go the MBS way and add a `BUILD_DATAMATCH` option that defaults to OFF?

**Comment by dennisklein** [comment]
wait, too fast, still needs to be picked to v18.8_patches
