### ISSUE TITLE
Return value check of GetSource()->InitUnpackers()

### ISSUE THREAD

**Issue by inkdot7** [FairRootGroup/FairRoot#1301]
The return value of `GetSource()->InitUnpackers()` is not checked in

https://github.com/FairRootGroup/FairRoot/blob/95b6b43de7ff33308989473c2cf90132effc3fa8/online/steer/FairRunOnline.cxx#L192

This leads to inconsistent results in r3broot, see https://github.com/R3BRootGroup/R3BRoot/issues/705

Should the return value be checked in `FairRunOnline::Init()` ?

**Comment by karabowi** [comment]
@inkdot7 , could you test the PR #1307 and leave us feedback on the performance?

**Comment by inkdot7** [comment]
Thanks for merging the fix!
