### ISSUE TITLE
Inconsistency in the file names of merged parameter files

### ISSUE THREAD

**Issue by ryotani** [FairRootGroup/FairRoot#1314]
I am analysing experimental data in multiple processes for different data sets simultaneously. In each process, several parameter files are merged within `FairParAsciiFileIo::open()` and `FairParRootFileIo::open()` functions. While they create new files after merging them, the naming rules are different. While the former creates an ASCII file in the working directory with the name of all_PID.par, the latter creates a root file in the directory where the original parameter file is stored with the name of allParams_yyyyMMdd_hhmmss.root. When I execute multiple analysis processes at the same time, some of them happen to crash as the merged parameter files created by `FairParRootFileIo::open()` within the same second.

My question/suggestion is the following: can we amend the naming rules for the merged parameter files to be consistent between FairParAsciiFileIo and FairParRootFileIo, naming after process IDs? If it's not practical, is it possible for us to add fifth argument in `FairParRootFileIo()` function as below?:
`Bool_t FairParRootFileIo::open(const TList* fnamelist, Option_t* option, const Text_t* ftitle, Int_t compress, TString newParFileName = "")`

Thanks for your consideration.

**Comment by karabowi** [comment]
Which `FairRoot` version do you use?
For around 10 months already we have a safer option to set a list of files to open in `FairParRootFileIo()`:
```
    auto parFile = std::make_unique<TFile>("parFile.root","RECREATE");
    parIn->MergeFiles(parFile.get(),parFilesList);
    parIn->open(parFile.get());

```

**Comment by ChristianTackeGSI** [comment]
Maybe we should consider providing a `MergeFiles` for the ASCII case as well?

So that people can decide on how the merged file should be named (or move the merging into a completely different part of their processing pipeline) there as well.

**Comment by ryotani** [comment]
Hi @karabowi, thank you for the comment.  I am using 18.6.2 and I realised apparently there are no descriptions with std::unique_ptr in these lines as you mentioned. Let me confirm: will this unique_ptr solve the issue I had before that some processes stopped when independent processes tried to open files with the "RECREATE" option simultaneously?

@ChristianTackeGSI 
I think it would be great if FairParAsciiFileIo could have a similar MergeFiles() function as FairParRootFileIo. But in any case, we can not change the name of merged parameter files.

**Comment by ChristianTackeGSI** [comment]
> @ChristianTackeGSI I think it would be great if FairParAsciiFileIo could have a similar MergeFiles() function as FairParRootFileIo. But in any case, we can not change the name of merged parameter files.

That's the actual point of the MergeFiles method: You decide on the name of the merged file (`"parFile.root"` in @karabowi's example). So you can come up with something that fits your needs (including a PID, moving to `/tmp`, what ever you think is good).

**Comment by karabowi** [comment]
You can use the 18.8.0 FairRoot, which is the first release to introduce the MergeFiles().
Did it fix the problem for you?

**Comment by ChristianTackeGSI** [comment]
18.8 only has MergeFiles for ROOT files.

I think the request was also for ASCII files.

I can try to create MergeFiles for ASCII as well, if that's helpful?

**Comment by karabowi** [comment]
I am on it right now.
