### ISSUE TITLE
FairRootConfig.sh sets FAIRROOTPAYTH to ""

### ISSUE THREAD

**Issue by klenze** [FairRootGroup/FairRoot#1326]
FairRootConfig.sh sets FAIRROOTPAYTH to "".
I used to think that was due to me configuring it wrong, but it is the same for the official cvmfs build: ``/cvmfs/fairsoft.gsi.de/debian10/fairroot/v18.8.0_fs_nov22p1/bin/FairRootConfig.sh``
``        export FAIRROOTPATH=""``

R3BRoot is assuming that $FAIRROOTPATH points to the FairRoot installation to use. I can manually set FairRootPath, but it would be nicer if it happened automatically.

**Comment by karabowi** [comment]
Do you run FairRoot's `FairRootConfig.sh` before building your experiment's software?
You don't need to, just set `SIMPATH` and `FAIRROOTPATH`.
Do you run the FairRoot's `FairRootConfig.sh` before calling your experiment's `config.sh`?
You shouldn't. It could lead to path mismatches.

Is R3BROOT using FairRoot's `WriteConfigFile.cmake` to create R3BROOT's `config.sh`?
Isn't `FAIRROOTPATH` set there properly?
`FAIRROOPATH` is not needed for using plain FairRoot, so it is not set.

**Comment by klenze** [comment]
> You don't need to, just set SIMPATH and FAIRROOTPATH.
okay, I did not know this. 
> FAIRROOPATH is not needed for using plain FairRoot, so it is not set.
This is not what is happening. It is set, just to "". 

Given that -- from my understanding -- a FairRoot compile depends on a specific FairSoft compile (aka SIMPATH), it would be nice to have an environment script which sets both of them instead of having to manually read FairRootConfig.sh and then setting the appropriate SIMPATH for that version. 

I am usually reluctant to bring up ROOT as a positive example, but ROOT's thisroot.sh does it all: the root binary is put into PATH so that people can run their macros, and CMAKE_PREFIX_PATH is set so that people can link to ROOT their cmake projects.

**Comment by karabowi** [comment]
In the current design we do not want to encourage users to call the config scripts multiple times in one shell.
If you need to simplify your work, you could implement a simple shell script that would do the job for you, f.e.
```
#!/bin/bash
eval $(grep SIMPATH $1/bin/FairRootConfig.sh)
export FAIRROOTPATH=$(realpath $1)
```

**Comment by dennisklein** [comment]
> Given that -- from my understanding -- a FairRoot compile depends on a specific FairSoft compile (aka SIMPATH)

Absolutely correct observation, asking the <Experiment>Root user to provide two paths instead of just one is indeed a strange design decision as it suggests false combinatorics.

**Comment by dennisklein** [comment]
> In the current design we do not want to encourage users to call the config scripts multiple times in one shell. If you need to simplify your work, you could implement a simple shell script that would do the job for you, f.e.
> 
> ```
> #!/bin/bash
> eval $(grep SIMPATH $1/bin/FairRootConfig.sh)
> export FAIRROOTPATH=$(realpath $1)
> ```

One could also do
```bash
export FAIRROOTPATH=<fairroot-install-dir>
export SIMPATH=$($FAIRROOTPATH/bin/fairroot-config --fairsoft_path)
```

**Comment by klenze** [comment]
Thanks, that looks reasonable.
