### ISSUE TITLE
Undefined symbols for architecture arm64 (install Fairroot -b v18.6.9 on MacBook Air M1, 2020)

### ISSUE THREAD

**Issue by EugeniaSpedicato** [FairRootGroup/FairRoot#1350]
I installed FairSoft with homebrew, after export and cmake, I find some problem with "make" command.

Mac is MacBook Air M1, 2020 with macOS Monterey 12.5. I want to build the FR version v18.6.9.
The error are reported below (FairMUonE is our FR based software, which has inside the fair::Logger things that give problems)

![Schermata 2023-02-13 alle 10 14 54](https://user-images.githubusercontent.com/48324041/218417764-6b3beb06-b82c-424b-9e6f-ea2325032b1c.png)

**Comment by EugeniaSpedicato** [comment]
Fairsoft:

1) brew update && brew doctor
2) brew tap fairrootgroup/fairsoft
3) brew install fairsoft@22.11
4) export SIMPATH=$(brew --prefix fairsoft@22.11)

FairRoot and FairMUonE:

1) cp -r fair_install/fairmuone/MUonE fair_install/FairRoot/.
2) add_subdirectory(MUonE) in FairRoot/CMakeLists.txt
3) cd FairRoot
4) mkdir build && cd build
5) cmake -DCMAKE_INSTALL_PREFIX="~/fair_install/FairRoot/install" ..
6) make -j3

and here is the error.

On centos7 and centos8 I was always able to install fairmu in this way, but also one year ago on my old Mac. So I suppose is this new arm64 the problem maybe

**Comment by dennisklein** [comment]
Can you share the content of the `CMakeLists.txt` file inside the `MUonE` subdirectory (or provide a link if it is hosted anywhere public)

**Comment by EugeniaSpedicato** [comment]
https://gitlab.cern.ch/mgoncerz/fairmuone/-/blob/master/MUonE/CMakeLists.txt

**Comment by dennisklein** [comment]
Between line 29 and 30, can you add a new entry `FairRoot::FairTools` in this file: https://gitlab.cern.ch/mgoncerz/fairmuone/-/blob/master/MUonE/MUonEReconstruction/Configuration/CMakeLists.txt#L30

**Comment by EugeniaSpedicato** [comment]
yes, still not working

**Comment by dennisklein** [comment]
Same error?

**Comment by dennisklein** [comment]
Try replacing `FairRoot::FairTools` with `FairLogger::FairLogger` (and make sure CMake configure phase is re-run, if in doubt, delete the FairRoot build directory and restart the whole FairRoot build after the change, just to be sure its not some artifact from a previous build not updating somehow)

**Comment by dennisklein** [comment]
Actually, it is a different error now. The first was in MUonEReconstructionConfiguration and this one is in MUonEGenerationConfiguration. But it is the same missing dependency, add `FairRoot::FairTools` or `FairLogger::FairLogger` to https://gitlab.cern.ch/mgoncerz/fairmuone/-/blob/master/MUonE/MUonEGenerators/Configuration/CMakeLists.txt#L36 as well.

**Comment by EugeniaSpedicato** [comment]
Ok it worked for all the classes with the exception of one.

Anyway, more than this error now I've another one which is not strictly related to FR but with arm64 register name for some variables (unknown register name 'xmm5' in asm). So I think that the issue can be closed as I think this is another kind of problem to which you're not related. 

Thank you for the helpful suggestions!

**Comment by dennisklein** [comment]
> So I think that the issue can be closed as I think this is another kind of problem to which you're not related.
>
> Thank you for the helpful suggestions!

No problem, anytime :)
