### ISSUE TITLE
Tutorial3 Sampler crashes when trying to remove a file

### ISSUE THREAD

**Issue by rbx** [FairRootGroup/FairRoot#1355]
https://cdash.gsi.de/testDetails.php?test=13503471&build=371764

After some investigation it looks like Sampler is trying to remove an intermediate file that it creates:
```
SysError in <TFile::TFile>: could not delete /shared/alfaci/jenkins/workspace/FairRootGroup_FairRoot_PR-1352@6/build/examples/advanced/Tutorial3/macro/data/testdigi_TGeant3.root.out.root (errno: 2) (No such file or directory)
[tut3-sampler][11:27:55.987090][FATAL][FairRootFileSink.cxx:66:FairRootFileSink] Error opening file /shared/alfaci/jenkins/workspace/FairRootGroup_FairRoot_PR-1352@6/build/examples/advanced/Tutorial3/macro/data/testdigi_TGeant3.root.out.root
```
Which is somewhere in:
https://github.com/FairRootGroup/FairRoot/blob/dev/examples/advanced/Tutorial3/MQ/sampler.cxx#L101-L103
And because the filename is hardcoded and this code is executed by different tests in parallel, they enter a race trying to create/delete this file.

Logically, the Sampler should only read an input file and send out data, it shouldn't have to create any intermediary files.
After consulting with @karabowi it seems that the reason for this output file is that `FairRunAna` needs to have a sink, otherwise it will also crash.

A quick/stupid fix would be to parameterize the intermediary filename with a session ID, then parallel tests will not crash each other when trying to recreate this file.

Better fix would be to make it possible for `FairRunAna` to work without a Sink.

**Comment by dennisklein** [comment]
> Better fix would be to make it possible for FairRunAna to work without a Sink.

+1

> A quick/stupid fix would be to parameterize the intermediary filename with a session ID, then parallel tests will not crash each other when trying to recreate this file.

Perhaps less stupid, but certainly also less quick would be to incorporate the session ID in a working directory name instead of propagating it down to each individual file.

**Comment by rbx** [comment]
> Perhaps less stupid, but certainly also less quick would be to incorporate the session ID in a working directory name instead of propagating it down to each individual file.

True, however the working directory for these tests is already parameterized. But FairRootFileSink (or some other FairRoot component) seems to follow its own rules when it comes to working directories and in this case it equals the directory of the input file (which is not parameterized, since the input file is reused for several tests).

**Comment by ChristianTackeGSI** [comment]
> Better fix would be to make it possible for FairRunAna to work without a Sink.

:+1:

Another (additional) option would be to create a dummy/mock sink, that just does nothing with the received data.

**Comment by karabowi** [comment]
@rbx , can we close this issue?

**Comment by rbx** [comment]
Yes.
