### ISSUE TITLE
Request: store random seed for event generation

### ISSUE THREAD

**Issue by Nepomuk** [FairRootGroup/FairRoot#147]
Hi,

I'm not sure if this is already available somewhere, if so, please give me a hint where to look. Anyways: I have the case that I want to rerun the simulation chain with different settings (more specifically, disable the FairLinks to see the difference, but this shouldn't affect the feature request).

Ideally, I could use the same random seed for EvtGen to generate the same events. So far, I didn't set this in my simulation macro, therefore I don't have access to the seed used.

My request would be to store the used seed somewhere (simparams.root maybe?) and make it accessible in case one would like to rerun with the same events.

Thanks,
-Andre

**Comment by MohammadAlTurany** [comment]
Hallo Andre,
This feature is now available in the dev branch of FairRoot. In the examples/simulation/Tutorial2 you can see how to get the random seed back from the parameter manager.
best,
Mohammad
