### ISSUE TITLE
CMake 3.27 support not working due to deprecation of Dart

### ISSUE THREAD

**Issue by olantwin** [FairRootGroup/FairRoot#1473]
**Describe the bug**
When building FairRoot with CMake ≥3.27, the configure fails as Dart has been removed.

https://cmake.org/cmake/help/latest/policy/CMP0145.html#policy:CMP0145

As of https://github.com/FairRootGroup/FairRoot/commit/35769f252071b83e45555f3473f91321d80dd322, FairRoot advertises compatibility with 3.27 policies.

**To Reproduce**
Configure FairRoot.

**Solutions**

1. Cap CMake version at 3.26 for now
2. Set CMP0145 to OLD
3. Don't `include(Dart)`

Happy to make a PR for the chosen solution. All three are tested and work.

**Comment by dennisklein** [comment]
Thx for the report! I can confirm it. Let's modernize and not `include(Dart)` any more. A PR would be very much appreciated. The `dev` branch is already modernized, the most recent bit I can see is https://github.com/FairRootGroup/FairRoot/commit/22c96f754. If possible, let's cherry-pick/backport the relevant commits from `dev`.

**Comment by dennisklein** [comment]
Starting from CMake 3.22 it is also supported to use `<CTestMeasurement>` instead of `<DartMeasurement>`, see https://gitlab.kitware.com/cmake/cmake/-/commit/373608831099bf96f568d9db5cb12a3f9092edf4. Probably to early to adopt this as we still support CMake 3.18 as minimum.

**Comment by olantwin** [comment]
> A PR would be very much appreciated. The `dev` branch is already modernized, the most recent bit I can see is [22c96f754](https://github.com/FairRootGroup/FairRoot/commit/22c96f754). If possible, let's cherry-pick/backport the relevant commits from `dev` to `v18.x_patches`.

Thanks, I'll have a look whether I can identify all the necessary commits.

**Comment by olantwin** [comment]
> A PR would be very much appreciated. The `dev` branch is already modernized, the most recent bit I can see is [22c96f754](https://github.com/FairRootGroup/FairRoot/commit/22c96f754). If possible, let's cherry-pick/backport the relevant commits from `dev` to `v18.x_patches`.

The only commit I found related to Dart is https://github.com/FairRootGroup/FairRoot/commit/22c96f754. Cherry-picking it works fine for the build, but some tests fail, but I don't have a comparison before the cherry-pick as the build is broken without.

**Comment by dennisklein** [comment]
In FairSoft we have a simple script [`bootstrap-cmake.sh`](https://github.com/FairRootGroup/FairSoft/blob/master/bootstrap-cmake.sh) with which you can install an older cmake version to compare (just modify the version veriable inside to your choice).

However, it seems there is now a human race condition happening, see #1476 and #1477. Seems @fuhlig1 is not aware of this discussion here.

**Comment by olantwin** [comment]
The test failures are all unrelated, as they also occur with CMake 3.26, so the cherry-pick seems fine.

@fuhlig1 Maybe it would be better to cherry-pick https://github.com/FairRootGroup/FairRoot/commit/22c96f754, as it also removes some code and files that become obsolete when using CTest, instead of only making the minimal change in `CMakeLists.txt`?
