### ISSUE TITLE
FairRoot v18.8.1 not working with FairSoft jan24 release

### ISSUE THREAD

**Issue by mgoncerz** [FairRootGroup/FairRoot#1490]
Running the cmake configuration command with newest FairRoot (v18.8.1) and FairSoft (jan24) release, gives an error:

> CMake Error at cmake/modules/FindROOT.cmake:94 (Math):
  Math cannot parse the expression: "6.30.02*10000 + 6.30.02*100 + 6.30.02":
  syntax error, unexpected exp_NUMBER, expecting end of file (5).
Call Stack (most recent call first):
  cmake/modules/FairMacros.cmake:431 (find_package)
  CMakeLists.txt:137 (find_package2)

> CMake Error at cmake/modules/FindROOT.cmake:95 (Math):
  Math cannot parse the expression: "6.30.02*10000 + 6.30.02*100 + 6.30.02":
  syntax error, unexpected exp_NUMBER, expecting end of file (5).
Call Stack (most recent call first):
  cmake/modules/FairMacros.cmake:431 (find_package)
  CMakeLists.txt:137 (find_package2)

It works fine with FairSoft nov22p1 (release previous to the problematic one).

I suspect the recent update of ROOT changed the way in which the (sub)versions are communicated, i.e. the splitting in findROOT.cmake is no longer working.

Tested on Ubuntu 23.04, cmake 3.25.1, gcc 12.3.0.

**Comment by dennisklein** [comment]
Can you try with the `v18.8_patches` branch of FairRoot? It contains https://github.com/FairRootGroup/FairRoot/commit/db27083b7b54e6cd3dacd77b95590d6bd652f9a6 which appears to address this issue.

I'll put on our agenda to prepare a `18.8.2` point release as well.

**Comment by dennisklein** [comment]
FYI: https://github.com/FairRootGroup/FairRoot/compare/v18.8.1...v18.8_patches

**Comment by mgoncerz** [comment]
I can confirm that this version configures and compiles fine for me.

**Comment by dennisklein** [comment]
I have also updated the release notes of FairSoft `jan24` to reflect this issue. It was actually mistakenly claiming that FairRoot v18.8.1 was tested which clearly it was not. Sry for the inconvenience.

**Comment by fuhlig1** [comment]
@mgoncerz,

could you please close the issue. If I understood the discussion correctly the problem was solved when using the fixed patch branch of jan24.

**Comment by mgoncerz** [comment]
@fuhlig1 Sure thing! Sorry about not doing it earlier.
