### ISSUE TITLE
[BUG] FairRootManager::GetObject is broken in FairRoot19

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairRoot#1556]
**Describe the bug**

The usage of `FairRootManager::GetObject` is broken after upgrading to FairRoot 19. This issue only occurs when `GetObject` is called more than once for one branch name. But such practice happens quite often as some branches (like event header) need to be used in different tasks at the same run.

This issue doesn't occur in FairRoot 18.8.

**To Reproduce**

1. Go to this [repository](https://github.com/YanzhaoW/test_repo/tree/fairroot_test).
2. Define env vairable `SIMPATH` and `FAIRROOTPATH` 
3. Compile and build project using FairRoot 18. Run executable `./write_data` and `./read_data`.
4. Compile and build project using FairRoot 19. Run executable `./write_data` and `./read_data`.
5. With FairRoot 19, outputs are all zeros. But if there exists only one task in `read_task.cpp`, then the output is correct.

**System information:**
 - OS: Debian buster
 - Compiler: gcc 13
 - Environment: FairSoft latest, FairRoot dev & 18.8

**Additional context**

1. This issue basically makes FairRoot 19 unusable for the data calibration, as event header is needed in almost every task.
2. Please do consider an alternative way of using `TTreeReader` used in `read.cpp` in the github repo.

@dennisklein @ChristianTackeGSI

**Comment by dennisklein** [comment]
I can confirm the behaviour.

**Comment by ChristianTackeGSI** [comment]
Just to be sure: The problem is the GetObject, right?

For example running write_data with 18.8 and then read_data with 19, would also fail?

We should write a (failing) test for FairRoot!

**Comment by dennisklein** [comment]
> For example running write_data with 18.8 and then read_data with 19, would also fail?

Yes, but only if used from more than one task as in his example code. With a single read task it works across versions.
