### ISSUE TITLE
Cannot register any branch in the Init() of FairGenerator

### ISSUE THREAD

**Issue by YanzhaoW** [FairRootGroup/FairRoot#1567]
**Is your feature request related to a problem?**

New branches cannot be registered during the calling of `FairGenerator::Init()`. Doing so will lead to a warning message:
```text
[WARN] FairRootFileSink::RegisterAny called for branch "MyBranchName" after FairRootFileSink::CreatePersistentBranchesAny has already completed. The branch will not be registered.
```
with no data written to the sink file.

**Describe the solution you'd like**

Call the `FairGenerator::Init()` before calling `FairRootFileSink::CreatePersistentBranchesAny` would fix the problem.

**Comment by fuhlig1** [comment]
@karabowi,

if I remember correctly we discussed the issue already some years ago. The problem was that the FairRoot state machine needs to call different states at defined places due to the interference with the state machines of the MC engines and it wasn't possible to change the order.

**Comment by karabowi** [comment]
I think I was able to find the solution in PR #1575.
@YanzhaoW can you test my branch and confirm that it fixes your use case?

**Comment by YanzhaoW** [comment]
@karabowi Thanks for the PR. I will test it out on next Monday and see whether it works or not.

**Comment by fuhlig1** [comment]
@YanzhaoW, 

does the changes from the PR work for you?

**Comment by YanzhaoW** [comment]
Yes, this is fixed for me.
