### ISSUE TITLE
terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by geniejhang** [FairRootGroup/FairRoot#158]
Hi.

I'm writing a software using the latest FairRoot.
I tried to narrow the range of energy loss of proton.
So, after `run -> Init()` command of FairRunSim object, I added

> ((TGeant4 *) gMC) -> ProcessGeantMacro("post.in");

Inside the `post.in` file is

```
/process/eLoss/minKinEnergy 10 MeV
/process/eLoss/maxKinEnergy 400 MeV
```

Then, the simulation codes gives an error as below.

> terminate called after throwing an instance of 'std::length_error'

Is this VMC problem? I tried the same thing with the extended example of GEANT4, TestEm5, and all worked fine with it.

Thank you in advance.
Genie

**Comment by MohammadAlTurany** [comment]
Hallo Genie,

In stead of adding your post.in, could you try to add the two lines to the "g4config.in"  macro in the gconfig directory?

best, 

Mohammad

**Comment by geniejhang** [comment]
Hi Mohammad.

Thank you for super fast reply.
I tried the way you suggested and it gives me the same result.
The error message was exactly the same.

Genie

**Comment by MohammadAlTurany** [comment]
Hallo Genie,
I tried with the example 3 (E03) in the VMC itself and I get the same error as you reported, It looks like a problem in the VMC. I will report it and let you know.
regards,
Mohammad

**Comment by kresan** [comment]
Hallo Genie,
does the problem with energy loss of proton still persist? I have just tried your commands for narrowing the energy loss range with geant4_vmc version 3.3 and it has worked without errors.
Best regards,
Dima

**Comment by geniejhang** [comment]
Hi Dima,

This was originally posted 3 years ago.
I guess it's fixed now by Mohammad's report.

However, I haven't tested it.

-Genie

**Comment by kresan** [comment]
Hi Genie,

Since we can not reproduce the error, I will close the ticket for now. If the problem appears again, please reopen or create a new issue.

Best regards,
Dima
