### ISSUE TITLE
FairRootManager crashes if running without an input file

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#170]
Hi FairRooters,

to analyze the test beam data of the MVD of PANDA the data is read in via an ifstream using boost::binary_iarchive. It is then analyzed with PandaRoot and stored using the FairRootManager.

This method causes a crash in the new implementation of the FairRootManager in FairRootManager::InitSource() because here a fRootFileSource is required which does not exist.

In the old version of FairRoot it was possible to run it without an input file.

Is it possible to add this functionality again to FairRoot or should the data be readin in a different way?

Cheers,

Tobias

**Comment by MohammadAlTurany** [comment]
Hi Tobias,
Radek solve this issue in the dev branch, could you test it and confirm? 
best, 
Mohammad

**Comment by MohammadAlTurany** [comment]
Issue solved
