### ISSUE TITLE
FairMQChannel has undefined behaviour when exception is caught.

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#228]
In multiple places in FairMQChannel there is undefined behaviour due to the fact once an exception happens, an error message is printed and then the flow continues, without a proper return statement. How is that supposed to work?

**Comment by rbx** [comment]
That's an oversight from my side, will send a fix in a bit.

There are also some situations where the channel configuration is
"invalid", but you can still amend it asynchronously within configurable
timeout period. For example if network address is invalid (it may be
updated asynchronously by DDS).

**Comment by MohammadAlTurany** [comment]
Problem solved!
