### ISSUE TITLE
Issues while using io manipulators to LOG() macro.

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#229]
I get a:

```
fairmq/logger/run/testLogger.cxx|29 col 15 error| invalid operands to binary expression ('basic_record_ostream<char_type>' and '__iom_t4<char>')
```

whenever I have something of the kind:

```
LOG(INFO) << std::setfill('*')
```

and similar. This is on a Mac using clang and boost 1.59. Any idea of what might be wrong?

**Comment by NicolasWinckler** [comment]
Hi,

yes it is a known boost issue of the 1.59.0 release. See https://svn.boost.org/trac/boost/ticket/11549
Please use the corresponding patch or the 1.58 version. Or a hack is to put an empty string between the LOG macro and the manipulator.

Best regards,

Nicolas

**Comment by ktf** [comment]
Ok, I'll pick up the patch for my builds. Feel free to close this.
