### ISSUE TITLE
EventHeader fMCEntryNo is wrong by +1

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#261]
The MC entry number in the event header has changed by +1 in contrary to older implementations. This causes problems with FairLinks becaus they now point to wrong event numbers if FairEventHeader::GetEntryNumber() is used to generate the FairLinks.

**Comment by MohammadAlTurany** [comment]
Hi Tobias,
I could not find any recent change which could cause this! can you tell me from which version or time this happened? 

best,

Mohammad

**Comment by TobiasStockmanns** [comment]
Hi Mohammad,
I cannot tell when this was changed. I just stumbeled about the problem when I checked the FairLinks for one of the PANDA sub-detectors. This uses FairEventHeader::GetEntryNumber() in contrary to FairRootManager::GetEntryNr() which is usually used by myself. I think these two should return the same number (which makes one of them obsolete) but FairEventHeader::GetEntryNumber() is always 1 higher than the FairRootManager version.

Cheers,

Tobias

**Comment by MohammadAlTurany** [comment]
Hallo Tobias,
The FairEventHeader does not have any method called GetEntryNumber, it has the GetMCEntryNumber which return the MC number.  GetEntryNr from the FairRootManager is the tree entry which could be different from the MC entry. The two numbers are not necessary the same!

best,
Mohammad
