### ISSUE TITLE
Pointer to the release information

### ISSUE THREAD

**Issue by matthiasrichter** [FairRootGroup/FairRoot#283]
I have been browsing through the [FairRoot web page](https://fairroot.gsi.de/) and came to the release information page on github. I then tried to reach it from the FairRoot home page on github, but I did not find any button or pointer. I suggest to include a link to README.md

Cheers
Matthias

**Comment by MohammadAlTurany** [comment]
Hi Matthias,

I added a poster to the README.md, it is now in the dev branch.

best,
Mohammad
