### ISSUE TITLE
Configuration for ex1-sampler-sink.json not valid JSON?

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#301]
I was looking at:

https://github.com/FairRootGroup/FairRoot/blob/dev/examples/MQ/1-sampler-sink/ex1-sampler-sink.json

and it occurred to me this is not valid JSON. This is because you have a dict with two keys which are identical and the behaviour is undefined as the parsing order is implementation dependant. Maybe we should change it to a list? I.e.:

```
   "devices": [
     {"id": "sampler", ...  },
     {"id": "sink", ...}
   ]
```

**Comment by NicolasWinckler** [comment]
Thanks for the suggestion. We will change it to list and modify our parser accordingly. Note however that our JSON parser can safely be used to fetch the device properties of the current JSON structure and does not depend on the device order

**Comment by ktf** [comment]
Yes, I figured that it simply considers them in order, however, this is in general not the case, effectively binding the configuration format to your parsing code, which is a bit against the philosophy of picking up JSON as configuration file format.

**Comment by NicolasWinckler** [comment]
Hello Giulio,
The FairmqParser::JSON can now parse json structure with array. You need to use the keys in plural ("devices", "channels", "sockets") to tell the parser that you expect an array. If you use the keys "device", "channel", "socket" in singular, the parser will behave as before.

**Comment by ktf** [comment]
Thanks! I will update the tutorial.
