### ISSUE TITLE
examples with non-C++ devices ?

### ISSUE THREAD

**Issue by sbinet** [FairRootGroup/FairRoot#310]
hi,

for fun (TM) I implemented a little `Go` based device (a sink) dialing some tcp address (over nanomsg) and printing back the message content.

It's here: https://github.com/sbinet-alice/go-ex-sink-mq

would there be interest in having such an example be incorporated into the port-folio of `FairRoot` examples ?
(I can flesh it out some more and have state-machine checks)

and just to make sure everything is also working in a slightly more complicated setting, I also created:
 https://github.com/sbinet-alice/go-ex-processor-mq

**Comment by MohammadAlTurany** [comment]
Hallo Sebastien
It would be great to have such an example!  
Could you add such an example to the [/examples/advanced/](https://github.com/FairRootGroup/FairRoot/tree/dev/examples/advanced) directory  in FairRoot?

Thanks,
Mohammad

**Comment by MohammadAlTurany** [comment]
Thanks Sebastien, it is now in the dev branch.

**Comment by fuhlig1** [comment]
Hi Sebastian,

could you also add a CMakeLists.txt? With the file we can build the example if a go compiler is found.
If you don�t know what to do you can also tell me which steps I have to do to compile and run the example.

Ciao

Florian



Am 11.03.2016 um 16:30 schrieb Sebastien Binet <notifications@github.com>:

**Comment by sbinet** [comment]
done. see #313.
I would need some guidance as I am rather illiterate in `CMake`-speak
