### ISSUE TITLE
ROOT 6.06.06 crashes whenever I tried to load classes

### ISSUE THREAD

**Issue by geniejhang** [FairRootGroup/FairRoot#403]
Hi.

I already posted in ROOT forum as in the link below,
https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=22057&p=96516#p96516

I know ROOT 6.06.06 is not officially supported in FairRoot now, but i leave it here for future use.

I don't know what causes the problem is, but somehow ROOT 6.06.06 crashes if I load any classes (let's say A) derived from FairRoot without loading any one of FairRoot classes (B) prior to A.

That is, Just loading B crashes. It should be A -> B.

Do you have any idea?

Thank you in advance.
Geine

**Comment by geniejhang** [comment]
It seems that there's a problem in FairLogger according to Philippe.
You can read through the post I left in the ROOTTalk ( the link in the above post )

Thank you for any response.

**Comment by MohammadAlTurany** [comment]
Hallo Genie,

I tried with ROOT 6.06.06 but could not see the problem with FairRoot and R3Broot. How can I reproduce this problem?  Can you send me an example or instruction how to reproduce it?

Cheers,

Mohammad

**Comment by geniejhang** [comment]
Thank you, Mohammad.

Let me do the third test.
I found that I made a mistake when disabling xrootd, so compiling root was not complete before.

Sorry for the mess.
I'll update the result here.

**Comment by geniejhang** [comment]
Sorry for the confusion.
It was XROOTD in ROOT.

I disabled it. But it was not completely disabled.
So, ROOT compilation was not complete.

Thank you!
