### ISSUE TITLE
invalid JSON configuration files

### ISSUE THREAD

**Issue by sbinet** [FairRootGroup/FairRoot#444]
hi,

it's probably related to #301.

the following python snippet does not produce the expected configuration:

```python
#!/usr/bin/env python2
import sys
fname = sys.argv[1]
import json
with open(fname) as f:
	d = json.load(f)
        print json.dumps(d, indent=4)
```

_e.g._
```sh
$> python2 ./foo.py examples/MQ/6-multiple-channels/ex6-multiple-channels.json
{
    "fairMQOptions": {
        "device": {
            "id": "broadcaster1", 
            "channel": {
                "name": "broadcast", 
                "socket": {
                    "rcvBufSize": "1000", 
                    "method": "bind", 
                    "address": "tcp://*:5005", 
                    "rateLogging": "0", 
                    "type": "pub", 
                    "sndBufSize": "1000"
                }
            }
        }
    }
}
```

while `examples/MQ/6-multiple-channels/ex6-multiple-channels.json` looks like:
```json
{
    "fairMQOptions":
    {
        "device":
        {
            "id": "sampler1",
            "channel":
            {
                "name": "data",
                "socket":
                {
                    "type": "push",
                    "method": "bind",
                    "address": "tcp://*:5555",
                    "sndBufSize": "1000",
                    "rcvBufSize": "1000",
                    "rateLogging": "0"
                }
            },
            "channel":
            {
                "name": "broadcast",
                "socket":
                {
                    "type": "sub",
                    "method": "connect",
                    "address": "tcp://localhost:5005",
                    "sndBufSize": "1000",
                    "rcvBufSize": "1000",
                    "rateLogging": "0"
                }
            }
        },

        "device":
        {
            "id": "sink1",
            "channel":
            {
                "name": "data",
                "socket":
                {
                    "type": "pull",
                    "method": "connect",
                    "address": "tcp://localhost:5555",
                    "sndBufSize": "1000",
                    "rcvBufSize": "1000",
                    "rateLogging": "0"
                }
            },
            "channel":
            {
                "name": "broadcast",
                "socket":
                {
                    "type": "sub",
                    "method": "connect",
                    "address": "tcp://localhost:5005",
                    "sndBufSize": "1000",
                    "rcvBufSize": "1000",
                    "rateLogging": "0"
                }
            }
        },

        "device":
        {
            "id": "broadcaster1",
            "channel":
            {
                "name": "broadcast",
                "socket":
                {
                    "type": "pub",
                    "method": "bind",
                    "address": "tcp://*:5005",
                    "sndBufSize": "1000",
                    "rcvBufSize": "1000",
                    "rateLogging": "0"
                }
            }
        }
    }
}
```

_i.e._ there are multiple `"device"` keys.
the same issue exists with multiple `"socket"` keys and (possibly) with multiple `"channel"` keys.

also, the `"sndBufSize"`, `"rcvBufSize"` and `"rateLogging"` keys are encoded as strings whereas they should be `JSON` numbers.

I believe we should either don't pretend these configuration files are `JSON`, or (my favorite option) fix these un-JSON-y files by using `"devices"`, `"channels"` and `"sockets"` keys.
(the `sndBufSize` and _cie_ issue is a nice-to-have one.)

-s

**Comment by rbx** [comment]
Regarding the multiple keys - the functionality to avoid this is already there, as you can see in other examples. This file was overlooked, I'll fix it in the next commit.

The integer values also work, you can use integer instead of string for sndBufSize, etc.

**Comment by sbinet** [comment]
fair enough.

what I am reaching at would be some kind of an official schema for the device(s) configuration, or really, anything under the `"fairMQOptions"` key.

_i.e._ something like that, in Go:

```go
type Config struct {
	Options Options `json:"fairMQOptions"`
}

type Options struct {
	Devices []Device `json:"devices"`
}

type Device struct {
	ID       string    `json:"id"`
	Channels []Channel `json:"channels"`
}

type Channel struct {
	Name    string   `json:"name"`
	Sockets []Socket `json:"socket"`
}

type Socket struct {
	Type        string `json:"type"`
	Method      string `json:"method"`
	Address     string `json:"address"`
	SendBufSize int    `json:"sndBufSize"`
	RecvBufSize int    `json:"rcvBufSize"`
	RateLogging int    `json:"rateLogging"`
}
```

this would help document what is accepted by `FairMQ` as a configuration file.

I can produce a little Go program that tries to load `JSON` files from the FairRoot repo and detect those which do not abide to the above schema.

**Comment by sbinet** [comment]
ah!

and what about the `"key"` and `"id"` keys in: `"examples/MQ/2-sampler-processor-sink/ex2-sampler-processor-sink.json"` ?
have they different meaning? different usage?

thanks.
-s

**Comment by rbx** [comment]
The `"id"` corresponds to the device ID, which should be unique across the topology. The `"key"` allows multiple devices to share same configuration. In the second example multiple processors are started with the same config. 

The Go snippet above it looks good, except socket can also be multiple. The program you mention would indeed be helpful.

The idea was to allow singular keys (device, channel, etc.) for cases where there is only one entry, to avoid having to create an array.

There is one more new feature that hasn't been used a lot yet - if no socket is specified, common settings defined under channel will be applied to the socket(s) of this channel. You can see it in the json of the third example.

**Comment by sbinet** [comment]
the command at:
https://github.com/sbinet-alice/fer/blob/master/cmd/fer-validate-json/main.go

gives something like this:
```sh
$> fer-validate-json -v ./example/cmd/testdata/ex2-sampler-processor-sink.json 
2016/11/09 10:44:36 ./example/cmd/testdata/ex2-sampler-processor-sink.json: use of "channel" keyword (device="sampler1")
2016/11/09 10:44:36 ./example/cmd/testdata/ex2-sampler-processor-sink.json: use of "socket" keyword (device="sampler1.data1")
2016/11/09 10:44:36 ./example/cmd/testdata/ex2-sampler-processor-sink.json: use of "socket" keyword (device="processor.data1")
2016/11/09 10:44:36 ./example/cmd/testdata/ex2-sampler-processor-sink.json: use of "socket" keyword (device="processor.data2")
2016/11/09 10:44:36 ./example/cmd/testdata/ex2-sampler-processor-sink.json: use of "channel" keyword (device="sink1")
2016/11/09 10:44:36 ./example/cmd/testdata/ex2-sampler-processor-sink.json: use of "socket" keyword (device="sink1.data2")
2016/11/09 10:44:36 [./example/cmd/testdata/ex2-sampler-processor-sink.json] validation FAILED
```

it doesn't detect `int` as `string`, yet.
(it wasn't clear whether this was something you wanted to enforce)

**Comment by rbx** [comment]
The singular words are valid if they are not repeated (e.g. "socket" for single object or "sockets" for an array).

Both int and string work for the numerical values from the perspective of the FairMQParser. Maybe put it as a warning?

**Comment by rbx** [comment]
I've updated all the non-standard JSON files. Now everything should be valid JSON. I also added a readme in fairmq/options to describe the details of the JSON configuration.

**Comment by sbinet** [comment]
ok.
the command `fer-json-validate` now produces:

```sh
$> fer-json-validate -v ./toto.json 
fer-json-validate: [./toto.json] validation FAILED:
ref={fairMQOptions {devices [{id sampler1 channel {name data1 socket {type push method bind address tcp://*:5555 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}channel {name data1 socket {type push method bind address tcp://*:5555 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}}{key processor channels [{name data1 socket {type pull method connect address tcp://localhost:5555 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}{name data2 socket {type push method connect address tcp://localhost:5556 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}]}{id sink1 channel {name data2 socket {type pull method bind address tcp://*:5556 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}}]}}
chk={fairMQOptions {devices [{id sampler1 channel {name data1 socket {type push method bind address tcp://*:5555 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}}{key processor channels [{name data1 socket {type pull method connect address tcp://localhost:5555 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}{name data2 socket {type push method connect address tcp://localhost:5556 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}]}{id sink1 channel {name data2 socket {type pull method bind address tcp://*:5556 sndBufSize 1000 rcvBufSize 1000 rateLogging 0}}}]}}
```

when `toto.json` has multiple `"channel"` keys.
less pretty, but still useful.

I have also produced a `json` reformatter a-la `clang-format` (or, rather, like `go fmt` from where `clang-format` draws its inspiration).
it's there:
 https://github.com/sbinet-alice/fer/blob/master/cmd/fer-json-fmt/main.go

automatically applying this kind of reformatter would reduce the git-diff-noise...

_wrt_ the `int` VS `string` issue, I think it would be better to be stricter to begin with (with maybe be more lenient if need be).
_i.e._ only accept `int` for the buffer sizes and rates.
