### ISSUE TITLE
Custom CMake Module FindProtobuf missing protobuf_generate_python

### ISSUE THREAD

**Issue by janmayer** [FairRootGroup/FairRoot#464]
The [custom CMake Module `FindProtobuf`](https://github.com/FairRootGroup/FairRoot/blob/master/cmake/modules/FindProtobuf.cmake) is missing the `protobuf_generate_python` command.

This custom module does not seem to be necessary at all, I deleted it from `<FairRoot-Install-Dir>/share/fairbase/cmake/modules/FindProtobuf.cmake` and the 
[build-in module from CMake](https://github.com/Kitware/CMake/blob/master/Modules/FindProtobuf.cmake) took over and found the FairSoft-installed protobuf without problems.

**Comment by dennisklein** [comment]
The `v18.0.0` release of FairRoot removed the custom `FindProtobuf` module.
