### ISSUE TITLE
build fails after rbx/shmem-zmq was merged

### ISSUE THREAD

**Issue by mkrzewic** [FairRootGroup/FairRoot#469]
Hi, this is on centos7, gcc4.8.5

`
DEBUG:O2:0: In file included from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.cxx:32:0:
DEBUG:O2:0: /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h: In member function 'FairMQMessagePtr FairMQDevice::NewSimpleMessage(const T&) const':
DEBUG:O2:0: /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:237:23: error: 'is_trivially_copyable' is not a member of 'std'
DEBUG:O2:0:          static_assert(std::is_trivially_copyable<T>::value, "The argument type for NewSimpleMessage has to be trivially copyable!");
DEBUG:O2:0:                        ^
DEBUG:O2:0: /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:237:51: error: expected primary-expression before '>' token
DEBUG:O2:0:          static_assert(std::is_trivially_copyable<T>::value, "The argument type for NewSimpleMessage has to be trivially copyable!");
DEBUG:O2:0:                                                    ^
DEBUG:O2:0: /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:237:52: error: '::value' has not been declared
DEBUG:O2:0:          static_assert(std::is_trivially_copyable<T>::value, "The argument type for NewSimpleMessage has to be trivially copyable!");
DEBUG:O2:0:                                                     ^
DEBUG:O2:0: /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:237:52: note: suggested alternatives:
DEBUG:O2:0: In file included from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/bind.hpp:22:0,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/msm/back/state_machine.hpp:44,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQStateMachine.h:32,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:31,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.cxx:32:
DEBUG:O2:0: /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/bind/bind.hpp:114:25: note:   'boost::_bi::value'
DEBUG:O2:0:  template<class T> class value
DEBUG:O2:0:                          ^
DEBUG:O2:0: In file included from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/expr.hpp:27:0,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/core.hpp:17,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/msm/msm_grammar.hpp:14,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/msm/back/state_machine.hpp:57,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQStateMachine.h:32,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:31,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.cxx:32:
DEBUG:O2:0: /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/traits.hpp:1161:5: note:   'boost::proto::value'
DEBUG:O2:0:      value(Expr const &e)
DEBUG:O2:0:      ^
DEBUG:O2:0: In file included from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/expr.hpp:27:0,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/core.hpp:17,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/msm/msm_grammar.hpp:14,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/msm/back/state_machine.hpp:57,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQStateMachine.h:32,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:31,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.cxx:32:
DEBUG:O2:0: /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/traits.hpp:294:16: note:   'boost::proto::result_of::value'
DEBUG:O2:0:          struct value
DEBUG:O2:0:                 ^
DEBUG:O2:0: In file included from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/expr.hpp:27:0,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/core.hpp:17,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/msm/msm_grammar.hpp:14,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/msm/back/state_machine.hpp:57,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQStateMachine.h:32,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:31,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.cxx:32:
DEBUG:O2:0: /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/proto/traits.hpp:824:16: note:   'boost::proto::functional::value'
DEBUG:O2:0:          struct value
DEBUG:O2:0:                 ^
DEBUG:O2:0: In file included from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/phoenix/core/value.hpp:15:0,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/phoenix/scope/local_variable.hpp:15,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/phoenix/operator.hpp:21,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/log/expressions.hpp:32,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/logger/logger.h:33,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQLogger.h:18,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQStateMachine.h:38,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.h:31,
DEBUG:O2:0:                  from /home/mkrzewic/alfa/sw/SOURCES/FairRoot/dev/0/fairmq/FairMQDevice.cxx:32:
DEBUG:O2:0: /home/mkrzewic/alfa/sw/slc7_x86-64/boost/v1.59.0_O2-1/include/boost/phoenix/core/is_value.hpp:30:16: note:   'boost::phoenix::expression::value'
DEBUG:O2:0:          struct value;
DEBUG:O2:0:                 ^
DEBUG:O2:0: [ 33%] Building CXX object trackbase/CMakeFiles/TrkBase.dir/FairGeaneUtil.cxx.o
DEBUG:O2:0: [ 33%] Building CXX object trackbase/CMakeFiles/TrkBase.dir/G__TrkBaseDict.cxx.o
DEBUG:O2:0: make[2]: *** [fairmq/CMakeFiles/FairMQ.dir/FairMQDevice.cxx.o] Error 1
DEBUG:O2:0: make[1]: *** [fairmq/CMakeFiles/FairMQ.dir/all] Error 2
DEBUG:O2:0: make[1]: *** Waiting for unfinished jobs....
DEBUG:O2:0: [ 34%] Linking CXX shared library ../lib/libTrkBase.so
DEBUG:O2:0: [ 34%] Built target TrkBase
DEBUG:O2:0: make: *** [all] Error 2
DEBUG:O2:0: 
`

**Comment by rbx** [comment]
Hi, this is fixed in the following commit.

**Comment by mkrzewic** [comment]
thanks, closing.
