### ISSUE TITLE
eth0 should not be the default network-interface for FairMQProgOptions

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#480]
As a user I would expect that I do not have to know about the network interface where I want to run. Right now `fairmq/options/FairMQProgOptions.cxx` uses eth0 which is only valid on a limited set of linux distributions but not on Mac or in general. A better behaviour is probably to select the interface of the default route.

**Comment by rbx** [comment]
Thanks for the suggestion @ktf! It is now implemented in the dev.

**Comment by MohammadAlTurany** [comment]
Solved
