### ISSUE TITLE
ZeroMQ can only be picked up from the system

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#512]
I have:

```
DEBUG:FairRoot:0: -- Looking for ZeroMQ - Found /opt/boxen/homebrew/opt/zeromq/include
DEBUG:FairRoot:0: -- Looking for ZeroMQ - Found version 4.2.2
....
DEBUG:FairRoot:0: In file included from /Users/ktf/work/active/sw/SOURCES/FairRoot/dev/0/fairmq/zeromq/FairMQTransportFactoryZMQ.h:23:
DEBUG:FairRoot:0: /Users/ktf/work/active/sw/SOURCES/FairRoot/dev/0/fairmq/zeromq/FairMQMessageZMQ.h:21:10: fatal error: 'zmq.h' file not found
DEBUG:FairRoot:0: #include <zmq.h>
```

I cannot actually find where zeromq is now added to the include path...

**Comment by dennisklein** [comment]
[Here](https://github.com/FairRootGroup/FairRoot/blob/dev/cmake/modules/FindZeroMQ.cmake#L121-L125) it gets imported and [here](https://github.com/FairRootGroup/FairRoot/blob/dev/fairmq/CMakeLists.txt#L201) it gets added to the include paths.

**Comment by dennisklein** [comment]
After a closer look, it turns out there was a bug. PR is pending.

**Comment by ktf** [comment]
Indeed, [here](https://github.com/AliceO2Group/AliceO2/pull/310) is where we are actually testing it. ;-). Should become all green once it actually works...

**Comment by matthiasrichter** [comment]
Actually, I have the case that a valid installation of ZeroMQ in the system is not correctly picked up any more.

**Comment by dennisklein** [comment]
> Actually, I have the case that a valid installation of ZeroMQ in the system is not correctly picked up any more.

@matthiasrichter With current FairRoot@`dev`?

**Comment by dennisklein** [comment]
@matthiasrichter Is this still an issue?

**Comment by matthiasrichter** [comment]
I have been checking from time to time whether it's solved, but now I have a couple of other accumulated build problems, I will come back to this issue later.

**Comment by matthiasrichter** [comment]
I can confirm that it is working with the current dev branch, thanks

**Comment by dennisklein** [comment]
thx, closing
