### ISSUE TITLE
Add conditional REQUIRED flag in find_package(GTest) in top level CMakeLists.txt

### ISSUE THREAD

**Issue by matthiasrichter** [FairRootGroup/FairRoot#534]
@dennisklein 
I ran into a problem with `find_package(GTest)` after updating.
After commit 46ce442d the main `CMakeLists.txt` correctly calls `find_package` without the `REQUIRED` flag, while it is called with `REQUIRED` flag in `fairmq/test/CMakeLists.txt`, which I suppose is also correct if `BUILD_TESTING` is set.

I suggest to handle the checks already in the top level CMakeLists.txt accompanied with a descriptive fatal error, e.g. GTest is required for BUILD_TESTING. This can guide much faster to the underlying problem.

**Comment by dennisklein** [comment]
> I suggest to handle the checks already in the top level CMakeLists.txt accompanied with a descriptive fatal error, e.g. GTest is required for BUILD_TESTING. This can guide much faster to the underlying problem.

I agree and will definitely keep your suggestion in mind if I have any say in the next round of cmake patches ;) But I feel I am stepping on too many toes at the moment with changing the way things are..

IMHO FairRoot's mixture of `BUILD_*`, `*_BUILD` and `WITH_*` switches as well as the conditional _automatic_ switches depending on `*_FOUND` and other things needs refactoring, streamlining and more documentation. Unfortunately, there are many opinions on this topic. See #511 for some recent discussion with @ktf. I don't even know @fuhlig1's opinion yet.

The rationale behind my last cmake cleanup in the patchset you mentioned is simple: I did not want to touch too much outside of the `fairmq` submodule yet until I understand the full picture (e.g. I do not like that FairMQ is only built as a _side effect_ as well as the nanomsg transport), but I needed some changes/fixes for my current work.

**Comment by matthiasrichter** [comment]
Hi Denis,
good, considered the discussion in #511, this issue here is a duplicate. The title should have alerted me already. Closing.

Ciao
Matthias
