### ISSUE TITLE
Reduce size of FairLink

### ISSUE THREAD

**Issue by sawenzel** [FairRootGroup/FairRoot#545]
Review the member structur of FairLink. Try to optimize the memory footprint.
Probably a few fields can be encoded in smaller types, packed into one single int, or using bitsets.

**Comment by TobiasStockmanns** [comment]
I packed the fileID into an unsigned char and the typeID into an unsigned short. This is smaller in size than both of them into one unsigned int and saves some bit shifting operations.

**Comment by sawenzel** [comment]
Ah .. didn't notice that the PR is already open: Can we try to link PR with issues ... just my mentioning them in the commit or PR message?

**Comment by MohammadAlTurany** [comment]
#547 is Merged
