### ISSUE TITLE
[FairMQ] RDMA transport

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#563]
In order to support efficient transport on high-bandwidth and low-latency fabrics like Infiniband or Converged Ethernet, we need a RDMA based transport.

Possible candidates:
1. [`libfabrics`](https://ofiwg.github.io/libfabric/)
2. Shared Memory Communications-RDMA (`SMC-R`)
    - [openfabric.org workshop talk](https://www.openfabrics.org/images/eventpresos/workshops2014/IBUG/presos/Thursday/PDF/05_SMC-R_Update.pdf)
    - [LWN article](https://lwn.net/Articles/696846/)
    - Merged into Linux 4.11 (not yet released) - [phoronix.com article](http://www.phoronix.com/scan.php?page=news_item&px=Linux-4.11-Networking)
3. `libfabrics` integration into `nanomsg`
    - Work done by Ioannis: [CISCO/CERN progress report](https://docs.google.com/document/d/1V172MRHIAZgu6A2KJVArBIXBvA9Hb31H5CFuFWLWdx8)

---

Update discussion from 10.3.2017:
- Preferred solution is to finish Ioannis' `ofi` integration into `nanomsg`.

---

Update 28.7.2017:

-
 https://www.openfabrics.org/images/eventpresos/workshops2014/IBUG/presos/Thursday/PDF/09_Sockets-over-rdma.pdf
- https://www.openfabrics.org/images/eventpresos/workshops2013/IBUG/2013_UserDay_Thur_1400_Bob-Russell-programming-concepts.pdf
- https://www.youtube.com/watch?v=ToFGhx5iN_E
- https://www.openfabrics.org/images/eventpresos/workshops2013/IBUG/2013_UserDay_Fri_1520_BobRussell-exs-talk.pdf

**Comment by dennisklein** [comment]
Ioannis' ofi nanomsg integration allows socket addresses like `ofi://address:port@tcp` which does not fit the current URL format in FairMQ. If we really need access to any nanomsg/ofi/fabric combination, then I propose `ofi+tcp://address:port` or `ofi+verbs://address:port` which is URL conform.

**Comment by MohammadAlTurany** [comment]
Another interesting talk about OFI:
[OPENFABRICS INTERFACES: PAST, PRESENT, AND FUTURE](https://www.openfabrics.org/images/eventpresos/2016presentations/105ofippf.pdf)

**Comment by dennisklein** [comment]
Kamino closed and cloned this issue to FairRootGroup/FairMQ
