### ISSUE TITLE
[FairMQ] Simplify logger

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#564]
The current `Boost.Log` based logger adds a lot of complexity, global functions and huge compile time resource usage. Investigate if and how to simplify, but maintaining the requirements:
- fast (dead code elimination, inlined)
- file and console output
- thread-safe

Alternatives:
- https://github.com/gabime/spdlog (MIT)
- https://gitlab.com/Marix/Einhard (GPL)

**Comment by rbx** [comment]
This is now fixed with the new logger (#704) in the dev.
