### ISSUE TITLE
[FairMQ] More ready-to-use devices

### ISSUE THREAD

**Issue by rbx** [FairRootGroup/FairRoot#565]
Implement common use case devices that are usable out-of-the-box.
- Sampler: 
  - send binary blob (is FairMQBenchmarkSampler sufficient?).
  - send file content.
- Merger (policy for merging decision).
- Sink:
  - receive and delete (default FairMQSink).
  - receive and dump to file (optionally with collecting until certain size is reached to optimize i/o).
- ...

**Comment by dennisklein** [comment]
Kamino closed and cloned this issue to FairRootGroup/FairMQ
