### ISSUE TITLE
[FairMQ] Improve FairMQChannel polling to be O(1)

### ISSUE THREAD

**Issue by rbx** [FairRootGroup/FairRoot#566]
Current I/O multiplexing implementation in FairMQ for waiting on data on Channels behaves O(n). Polling unix sockets - hidden in the underlying zeromq/nanomsg libraries - is already O(1). All transports we currently support can expose the relevant operating system file descriptors which enables the usage of O(1) polling system calls - kqueue for MacOSX and epoll for Linux. Boost.Asio io services already nicely abstract such system APIs for us and according to [Integrating Boost Asio with ZeroMQ](https://rodgert.github.io/2014/12/24/boost-asio-and-zeromq-pt1/) integration is feasible.

[A mockup](https://gist.github.com/rbx/b51bd7d1fc7d32886bd6aebc53e98638) shows that the edge-triggered interface exposed by ZeroMQ causes socket starvation in a simple implementation -> Investigate how [AZMQ](https://github.com/zeromq/azmq)/[czmq zloop](https://github.com/zeromq/czmq) solve this.

**Comment by dennisklein** [comment]
Kamino closed and cloned this issue to FairRootGroup/FairMQ
