### ISSUE TITLE
FairMQProgOptions default value

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#568]
Unless I miss something trivial, it looks like there is no way to specify a default value for `FairMQProgOptions::GetValue`. Is it possible to add it?

**Comment by rbx** [comment]
You can specify default values when you add fields to `FairMQProgOptions` via `addCustomOptions`, like here:
https://github.com/FairRootGroup/FairRoot/blob/master/examples/MQ/1-sampler-sink/runExample1Sampler.cxx

**Comment by ktf** [comment]
Doh, sorry for the noise.
