### ISSUE TITLE
[FairMQ] Add documentation

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#573]
- [x] Extend the Transport matrix for supported address formats.
- [x] Add a section which describes the various Message factories.
- [x] Add a section which gives examples and hints on how to write unit tests
- [x] Document NewPoller factory.
- [x] Document Channel.
- [x] Add Development/Testing/MultipleDevices section.
- [x] Add description of the JSON format for FairMQParser.
- [x] Document ParameterMQServer.
- [x] Extend threading documentation (state handlers run in their own thread).
- [x] Document common devices.
- [x] Document introspection options.

**Comment by rbx** [comment]
Close for now, since all the above docs are now added. Can re-open and extend the list if something else becomes available.
