### ISSUE TITLE
Singelton Pattern

### ISSUE THREAD

**Issue by MohammadAlTurany** [FairRootGroup/FairRoot#576]
Improve singleton implementation in:

- [x] FairRootManager
- [ ] FairRunAna
- [ ] FairRunSim
- [ ] FairRun

**Comment by sawenzel** [comment]
See #640 : I think that the FairRootManager is not yet a proper singleton since the destructor is never called.

**Comment by MohammadAlTurany** [comment]
Issue #640 is solved in #653

**Comment by MohammadAlTurany** [comment]
Changing FairRun, FairRunAna and FairRunSim will:

- break all user code for all experiments.
- Need a huge change in design as FairRunAna and FairRunSim inherits from FairRun

So it will not be changed.
