### ISSUE TITLE
[FairMQ] Replace PStreams with Boost.Process

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#589]
- [x] Implement `fair::mq::test::execute` with Boost.Process
- [x] Drop PStreams dependency
- [x] Move `fair::mq::test::execute` to `fair::mq::tools::execute`
- [ ] ~~Fix [CID 169667](https://scan9.coverity.com/reports.htm#v32049/p11256/g32049g/fileInstanceId=17262616&defectInstanceId=3348694&mergedDefectId=169677)~~ Cannot locate it anymore, let's see if it occurs again with new implementation (edited by rbx).

**Comment by rbx** [comment]
Fixed with #715.
