### ISSUE TITLE
-DDEBUG conflict with Fair{ROOT,MQ} loggers.

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#591]
It's rather common practice to pass `-DDEBUG` as compilation option to enable code sections which contain debug code:

```C++
#ifdef DEBUG
...
#endif
```

This happens for user code and for third party externals. However this conflicts with `logger_def.h` and `FairLog.h` where `DEBUG` is used as severity_level. Is it possible to either protect such a header against `DEBUG` being defined or have a less generic name used?

**Comment by rbx** [comment]
With our new logger implementation (#704) the DEBUG is still defined for backwards compatibility, but all severity names are also available in lowercase (and have been switched throughout the code base to lowercase use). Hopefully in time we can remove the uppercase ones completely.
