### ISSUE TITLE
FairMQDevice and multithread code

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#616]
This is a bit of a summary of a discussion I already had with @rbx and @sawenzel, regarding the side effect of current threading model in FairMQ.

The issue has been spotted by trying to run code (a GEANT3 simulation, but that's details) that while not multithreaded per se (and actually supposedly "multithread aware"), it still fails due to multithread issues. This is due to executing `InitTask()` and `OnData` callbacks in two different threads and executing callbacks off the main thread.  This has multiple failure modes, for example if `InitTask()` initialising a `thread_local` variable which cannot be accessed by the `OnData` callback or the code in  the `OnData` callback expecting to be running  in the main thread. Part of this can be mitigated using `Init()` (which runs on in the same thread as the callback) but it would still create problems to code which expects to be run on the main thread (I think this actually happens for some OpenMP implementations).

I therefore suggest the following two actions:

* Document the issue and mention it in the `FairMQDevice::InitTask` and `FairMQDevice::Init` doxygen documentation
* Evaluate whether it's possible to run all the user code always on the main thread, having the message passing event-loop happen in the secondary thread.

**Comment by rbx** [comment]
With #631 InitTask will also run in the worker thread (same thread as for all other state handlers). I added doxygen comments regarding this and the FairMQ docs also describe this in the State Machine section.

I did tests with OpenMP and TBB, successfully running both inside OnData handlers.
For now we will keep running the handlers in the worker thread, unless another use case becomes apparent.
