### ISSUE TITLE
Have a device signal other devices that they should quit

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#623]
Hi,

I would like to have a setup where I have a producer, a processor, and a sink. When the sink decides it has done enough work, I would like all the three of them to quit. For example I am running a test were I read from file, apply some filter and then write to file a fixed number of messages.

I suspect I can do this via the Control plugin, but I am not sure how. Can someone provide a link to an example? If it's not possible and you consider it a valid use case, can a mean to do so be added?

**Comment by rbx** [comment]
Hi Giulio,

The devices themselves have no knowledge/control of state of other devices in the topology, this should be done, as you are correctly guessing, by the control plugin.

With our new plugin system we are now converting our three typical run cases into control plugins:
- *interactive* (device states controlled by user input)
- *static* (predefined set of device state transitions) 
- *DDS* (communicating with a central control system) control plugins.

They are currently done outside of the plugin system (by `fairmq/tools/runSimpleMQStateMachine.h`).
With these new plugins you will have an example of achieving what you want.

We do something very similar to what you described for many of our functional tests, where one (or more) device finishes some work, quits and the test script shuts down the rest of the devices. The devices listen to interrupt signals, and will do a graceful shutdown (with proper state transitions) on `SIGINT`.

Example: https://github.com/FairRootGroup/FairRoot/blob/dev/examples/MQ/2-sampler-processor-sink/testMQEx2.sh.in

**Comment by dennisklein** [comment]
> With our new plugin system we are now converting our three typical run cases into control plugins ...

@ktf You can track my progress on these topics in #561. I just came back this week from vacation and now focussing on this todo list.

**Comment by ktf** [comment]
Ok, I guess what I really need is to have a way to express in my workflow specification what to do when a device quits. I could prune all the unique dependencies of the device, quit all the devices, restart a new device. I will have to think a bit about the various usecases.
