### ISSUE TITLE
undefined references

### ISSUE THREAD

**Issue by miharenthas** [FairRootGroup/FairRoot#677]
Hi, there are two (it seems) undefined references in dev:

./libTutorial4.so: undefined reference to `FairTutorialDet4GeoHandler::FillDetectorInfoArray(int)'
./libFairDataMatch.so: undefined reference to `FairMCObject::PosInList(std::pair<int, int>)'

This would prevent GNU ld from linking executables against those two libraries --or those libraries which require those two.

Should be an easy fix --if you're interested, I can whip up a feature branch for it tomorrow.

**Comment by MohammadAlTurany** [comment]
Hi,
Sure, please create a PR with the fix.
Thanks.
Mohammad

**Comment by miharenthas** [comment]
Hi, as it turns out: there's no need and those two broken references have already been fixed --possibly, in the last two commits on dev.
Thanks!
