### ISSUE TITLE
Did ROOT break std::cout (again)?

### ISSUE THREAD

**Issue by miharenthas** [FairRootGroup/FairRoot#705]
On the 17th of November, last year, I raised issue #67 in FairSoft about this... maybe I'll have better luck here.

There's a recurring break when I try to run simulations (with a _program_ not a script):

[ostream_screwup.txt](https://github.com/FairRootGroup/FairRoot/files/1615045/ostream_screwup.txt)

Any ideas about where does this come from and how to solve it (short of getting rid of every std::cout in scripts loaded at runtime)?
Thanks.

There's another problem, also, which is a break on exit when ROOT tries to deinstantiate itself but that's for a different issue... and I don't think that depends on anything you or I are doing.

**Comment by MohammadAlTurany** [comment]
Hallo,
Just to understand and reproduce this problem:
1. You do not have a macro but an executable (compiled code) that calls your simulation?
2. Which system and compiler you use, which version of FairSoft and FairRoot 
best,
Mohammad

**Comment by miharenthas** [comment]
Hi, thanks for your answer!

1. Yes, I have compiled code linking into root. It has been working for a long while --and didn't break because something obvious happening to Fair{Soft,Root}, or to it.
2. I am on par with master for FairSoft and on f7b97f7f93a67d3bada4a6c4efe916d87ae163ec for FairRoot (23 commits behind dev, will pull soon).

Best,
L.

**Comment by MohammadAlTurany** [comment]
Hi,
Unfortunately I could not reproduce this problem with FairRoot examples. Is your Code available on GitHub? could you point me where to git it? 
Best,
Mohammad

**Comment by miharenthas** [comment]
Hi,

Yes it is on my github: it's in the abkg_driver repo, in the "simulator" directory. But it uses some additional detectors in R3BRoot and in general I'd say it's too much trouble to get that whole software running just to see if it fails.

I've been just trying on Mac OS X (10.13.2 --> using clang + Apple's stdlibc++ instead of GNU's version, which are different) and it doesn't trip out on std::cout there, with ROOT coming from Homebrew. I still get the break on exit (which we aren't talking about here) and as I imagined is a problem with ROOT and therading and new malloc features that came up recently.

What operating system and glibc version did you use for the test?
What did you do? (maybe I can also try to see if your attempt blows up on my machine or not...)

Thanks a lot!
Cheers,
L.

**Comment by MohammadAlTurany** [comment]
Hi,

I am using MacOs X 10.13.2 with  Apple LLVM version 9.0.0 (clang-900.0.39.2). ROOT is build within FairSoft.
I compiled the run_tutorial1.C macro in Tutorial1 and run it (FairRoot/examples/simulation/Tutorial1).
To do that:

1. Start ROOT and call 
gSystem->AddIncludePath("$PATH_TO_FAIRROOT/examples/common/passive/")
This is needed as it contains  FairCave.h 
2.  call the macro "load_all_libs.C" in Tutorial1/macro directory to load the libraries
3.  You need to add the includes to the macro before you can compile it ( here it is [run_tutorial1.C](https://github.com/FairRootGroup/FairRoot/files/1618746/run_tutorial1.C.txt)) 
 
4. call .x run_tutorial1.C++ to compile the macro and execute it

best,
Mohammad

**Comment by miharenthas** [comment]
I'll try.

So we had the same system, but maybe not the same ROOT (you probably have 6.10/08 while I'm using 6.12/04; on Fedora 27 I'm running 6.10/08)...

The feeling I have is that the criticality on GNU+Linux is JIT-compiling a macro from within an executable, but can be that from CLING directly the screwup will happen. I'll let you know.

**Comment by MohammadAlTurany** [comment]
Yes, I am using ROOT 6.10/08

**Comment by miharenthas** [comment]
I seem to get just a bunch of errors when trying to compile the macro, but that might be due to the fact that I don't know how to use "macros"...

**Comment by MohammadAlTurany** [comment]
Did you try the macro above ([run_tutorial1.C](https://github.com/FairRootGroup/FairRoot/files/1618746/run_tutorial1.C.txt)) ?

**Comment by miharenthas** [comment]
Yes, but I get stuck with the said bunch of errors. It looks like the JIT compiler isn't able to find libraries and headers (or consider them in the right order: lots of "incomplete type" complaints).

I source'd the config.sh in the build folder (and also I installed the whole thing in /usr/local/ diorectly, so it's visible to the system by default.
Also, the programs that need {Fair,R3B}Root are able to link and execute correctly for the most part.

Looking at the problem in GDB, it seems that at some point an invalid address is passed to std::cout as a string.
```
Thread 1 "sbkg" received signal SIGSEGV, Segmentation fault.
std::ostream::sentry::sentry (this=0x7fffffffb860, __os=...)
    at /usr/src/debug/gcc-7.2.1-20170915/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream.tcc:51
51	      if (__os.tie() && __os.good())
(gdb) list
46	    basic_ostream<_CharT, _Traits>::sentry::
47	    sentry(basic_ostream<_CharT, _Traits>& __os)
48	    : _M_ok(false), _M_os(__os)
49	    {
50	      // XXX MT
51	      if (__os.tie() && __os.good())
52		__os.tie()->flush();
53	
54	      if (__os.good())
55		_M_ok = true;
(gdb) print __os
$1 = (std::basic_ostream<char, std::char_traits<char> > &) @0x7fffed32ce20: {<std::basic_ios<char, std::char_traits<char> >> = <invalid address>, 
  _vptr.basic_ostream = 0x0}
```
Another mildly weird thing is that there's a considerable thread-spawning happening even when I disable threading in my code (it used to be safe and don't touch ROOT stuff anywhere except in the main thread).

This on Fedora 27, I'll let you know what happens on my Mac in a minute.

**Comment by MohammadAlTurany** [comment]
Any News here?

**Comment by miharenthas** [comment]
No, not really: I also couldn't reproduce the problem working in CLING and also with very simple programs.
I just decided to do something else instead of using those setup macros.

**Comment by RalfKliemt** [comment]
Hi,

I'd like to revive this issue as we stumble across it with unit testing in PandaRoot.
- We use FairSoft nov20, FariRoot 18.6.1 from the gSI cvmfs
- We use teh following preliminary code of PandaRoot:  
    ```git fetch "https://git.panda.gsi.de/SGaiser/PandaRoot.git" Unit-tests-for-PndPidCorrelator
git checkout -b "SGaiser/PandaRoot-Unit-tests-for-PndPidCorrelator" FETCH_HEAD
```
- After the build step we try to run `build/bin/TestPidCorrelatorInit` which works on this branch
- Putting a cout to `source/gconfig/Geane.C` produces the segfault with the cout sentry when running the executable

From the messages above I gather that tis is more of a ROOT + executables problem, right?

Cheers!
