### ISSUE TITLE
[FairMQ] Binding doesn't work when using 'localhost' instead of 127.0.0.1

### ISSUE THREAD

**Issue by knopers8** [FairRootGroup/FairRoot#711]
When trying to open a FairMQ channel with following configuration:
```
{
  "fairMQOptions": {
    "devices": [
      {
        "id": "sink1",
        "channels": [
          {
            "name": "dpl-out",
            "sockets": [
              {
                "type": "sub",
                "method": "bind",
                "address": "tcp://localhost:26525",
                "sndBufSize": 10,
                "rcvBufSize": 10,
                "rateLogging": 1
              }
            ]
          }
        ]
      }
    ]
  }
}
```
I get plenty of:
`Failed binding socket d31e96a5-61da-444a-a07a-644aeb28ca46.dpl-out[0].sub, reason: No such device`
It works when using 127.0.0.1 instead of localhost. Also, it happens only for binding, connecting works nicely.

**Comment by rbx** [comment]
It is rejected by ZeroMQ, since [it only accepts addresses for bind](http://api.zeromq.org/2-1:zmq-tcp#toc3). But perhaps we can make the translation on the framework level to keep this more consistent.

**Comment by knopers8** [comment]
I can live with the way it is now, but it surely makes the usage a bit more unclear, especially for new users. So, from my point of view, making the translation would be a good idea.

**Comment by ktf** [comment]
or at least you should have a message pointing to the zeromq documentation about possible values...

**Comment by dennisklein** [comment]
Kamino closed and cloned this issue to FairRootGroup/FairMQ
