### ISSUE TITLE
 FairRoot uses wrong ROOT during compilation

### ISSUE THREAD

**Issue by knopers8** [FairRootGroup/FairRoot#729]
I have 'standalone' ROOT installed on the system. 

During compilation with aliBuild, FairROOT seems to be using root-config in` /usr/bin/root-config` instead of the one in the ROOT compiled with aliBuild ( `/home/pkonopka/alice/sw/slc7_x86-64/ROOT/v6-12-04-1/bin/root-config` in my case ), which fails compilation. E.g.
```
fatal error: 'TMCtls.h' file not found
#include "TMCtls.h"                     // for multi-threading
```

Doing `mv /usr/bin/root-config /usr/bin/.root-config` helps.
I was redirected from [here](https://github.com/alisw/alidist/issues/1015).

**Comment by MohammadAlTurany** [comment]
Hi,
In FairRoot the [FindROOT.cmake](https://github.com/FairRootGroup/FairRoot/blob/dev/cmake/modules/FindROOT.cmake) is used to find root-config , looking in this file you can see:

`Set(ROOT_CONFIG_SEARCHPATH`
 ` ${ROOT_DIR}/bin` 
  `${SIMPATH}/bin` 
 ` ${SIMPATH}/tools/root/bin` 
 ` $ENV{ROOTSYS}/bin ` 
`)`
`...`
`Find_Program(ROOT_CONFIG_EXECUTABLE NAMES root-config `
`             PATHS ${ROOT_CONFIG_SEARCHPATH}`
`            NO_DEFAULT_PATH`
`           )`

So we do not search in system path at all, but if you have in your environment for any reason a ROOTSYS defined then it will be taken, and I guess this is the reason for your problem.

Could you please check your profile or bash settings if there is a ROOTSYS defined somewhere?

**Comment by knopers8** [comment]
Hello,
I checked in all profile and bash settings, ROOTSYS is declared in none of these. Also, freshly started terminal has no ROOTSYS declared. After doing `alienv load O2/latest` it is `ROOTSYS=/home/pkonopka/alice/sw/slc7_x86-64/ROOT/v6-12-04-2` (of course if FairRoot compiles before, with my workaround).

As I can see in [logfile](https://github.com/FairRootGroup/FairRoot/files/1727799/log.txt), there is clearly `-DROOTSYS=/home/pkonopka/alice/sw/slc7_x86-64/ROOT/v6-12-04-2` given to cmake.
I also modified FindROOT to show ROOTSYS from there and still I get:
```
-- Looking for Root...
-- /home/pkonopka/alice/sw/slc7_x86-64/ROOT/v6-12-04-2
-- Looking for Root... - Found /usr/bin/root
-- Looking for Root... - Found version is 6.12/04 
```

**Comment by knopers8** [comment]
It looks like Find_Program() still prefers `/usr/bin/root-config ` even when proper search path is given:
```
-- ROOT_CONFIG_SEARCHPATH:
-- /bin/bin/tools/root/bin/home/pkonopka/alice/sw/slc7_x86-64/ROOT/v6-12-04-2/bin
# Find_Program(...) invoked
-- ROOT_CONFIG_EXECUTABLE:
-- /bin/root-config
```

**Comment by dennisklein** [comment]
I can see the problem. By accident the first paths listed in the `ROOT_CONFIG_SEARCHPATH` are containing a root-config exeutable. This is a bug. The `find_program` call should use `HINTS` parameter with just the search prefixes and the `PATH_SUFFIXES` parameter with just the value `bin`.

**Comment by dennisklein** [comment]
@knopers8 Could you please verify if #731 fixes your problem?

**Comment by knopers8** [comment]
It works now, thanks!

**Comment by dennisklein** [comment]
:)
