### ISSUE TITLE
Is `FairVersion.h` generation forcing a final copy for every install target?

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairRoot#733]
I've the impression that the fact that `FairVersion.h` is generated for every invocation of `make` is causing a final round of cp for every install target, making a simple, empty build slow. Can you confirm that and eventually fix it?

**Comment by fuhlig1** [comment]
Hi,

I rechecked more carefully and I didn't find that _FairVersion.h_ is generated for every invocation of _make_. The file is only regenerated when the git version (commit hash) has changed which is exactly what we want.

**Comment by ktf** [comment]
yes, the file is not touched, however I suspect the target is always marked as dirty (because you always check if the commit hash is the same) and triggers a refresh. This is the only reason I could find to explain the full refresh of the libraries in O2 when I type make install (regardless of the libraries being already up-to-date).

**Comment by ktf** [comment]
I found at least one problem (i.e. see #770). Will let you know if this actually is the root cause of what I am seeing.
