### ISSUE TITLE
Make a special repository for FairMQ

### ISSUE THREAD

**Issue by valvy** [FairRootGroup/FairRoot#736]
# Split FairMQ from FairRoot
## Introduction
Students at the Amsterdam University of Applied sciences will in the future learn how to work with clusters and load balancers. For this they learn how to use Ansible, Zookeeper and we would like them to learn FairMQ as well. For this purpose we use the Raspberry Pi 3.
![whatsapp image 2018-02-28 at 15 57 51](https://user-images.githubusercontent.com/5433860/36795198-ab0c1544-1ca2-11e8-894f-98199c0be122.jpeg)

Due the limited hardware capabilities, it's not practical (and for now impossible) to run a full version of FairRoot on a Raspberry Pi, since we do not need the full version of FairRoot we suggest to place FairMQ in a separate repository with its own build and installation scripts.

## Why use a separate repository?
I already forked the code and created a separate [repository](https://github.com/valvy/PiFairMQ) containing FairMQ's code which was tested on the Raspberry Pi 3. It is faster to compile on the 'limited' hardware and doesn't completely overwhelm a small SD-card.

If FairMQ receives its own dedicated repository, students can always use the latest version of FairMQ while I don't have to backport all features from the FairRoot SDK. Also if a students find an issue they can push it to a central repository instead of both to my repository and to the FairRoot SDK.

**Comment by MohammadAlTurany** [comment]
Dear Heiko,
I see your point and agree with you that it make much sense to separate the FairMQ part from the rest of the FairRoot, one way to do it is the separate repository as you pointed out. At the moment we working on re-writting and modernising the CMake infrastructure of the whole project (PR #632 ). We also went to move to a new build and dependancy handling system [AlfaBuild/AlfaDist](https://github.com/FairRootGroup/alfadist). After these two major changes it will be trivial to separate the FairMQ from FairRoot and cleanly re-organize the dependancies.

**Comment by dennisklein** [comment]
@valvy We invite you to test our new [FairMQ](https://github.com/FairRootGroup/FairMQ) repo and we would appreciate your feedback: e.g. if it solves your use case and/or if you see any issues still. Some of the example code specific to FairMQ still resides in the FairRoot repo, but we plan to move it in the next weeks.

**Comment by dennisklein** [comment]
We believe this issue is resolved with the first stable release of the new [FairMQ repo](https://github.com/FairRootGroup/FairMQ/releases). Feel free to reopen or create a new issue, if you find any problems.
