### ISSUE TITLE
TList::Clear error

### ISSUE THREAD

**Issue by geniejhang** [FairRootGroup/FairRoot#738]
Hi.

This issue might be solved in the next version when you decide to use ROOT 6.12.06 or higher.
I constantly get the error below.

Error in <TList::Clear>: A list is accessing an object (0x7f652f199880) already deleted (list name = TList)

It happens even when I load the ROOT file created by FairRunSim and just close it without do anything.
The commits from Nov. 12th to Dec. 7th, 2017 are the updates on TList applied in ROOT 6.12.06 I guess in the following link.
https://github.com/root-project/root/commits/master/core/cont/src/TList.cxx

Just for your information :)
It would be great if you have any idea how to fix it even if it will be applied later on.
I'll be happy to apply and test it!

Thank you!

**Comment by geniejhang** [comment]
I think it's nothing to do with FairRoot.
It's just from the new version of ROOT.

**Comment by geniejhang** [comment]
It looks like it happens with ROOT installed with FairRoot and FairSoft.

**Comment by MohammadAlTurany** [comment]
Hi,
I am trying to reproduce this error but I could not, I am using the newest FairSoft ([may18](https://github.com/FairRootGroup/FairSoft/tree/may18)) and the dev branch of FairRoot. After running Tutorial1 I did the following:

> root [0] TFile *f=new TFile("tutorial1_TGeant3_pions.mc_p2.000_t0_n10.root") 
(TFile *) 0x7fe35dc69450
root [1] f->ls()
TFile**		tutorial1_TGeant3_pions.mc_p2.000_t0_n10.root	
 TFile*		tutorial1_TGeant3_pions.mc_p2.000_t0_n10.root	
  KEY: TFolder	cbmroot;1	Main Folder
  KEY: TList	BranchList;1	Doubly linked list
  KEY: TList	TimeBasedBranchList;1	Doubly linked list
  KEY: FairFileHeader	FileHeader;1	
  KEY: TTree	cbmsim;1	/cbmroot
root [2] f->Close()
root [3] .q
>

So I do not see the error, could you please test it or let me know how to reproduce it.

best,

Mohammad
