### ISSUE TITLE
FairMQProgOptions incomplete type when subclassing FairMQDevice

### ISSUE THREAD

**Issue by Barthelemy** [FairRootGroup/FairRoot#744]
When creating a Device by subclassing FairMQDevice, we get the error when using `getConfig()` :
```error: member access into incomplete type 'const FairMQProgOptions'```

One has to add `#include "options/FairMQProgOptions.h` in the subclass to avoid it. 

Could you change the forward declaration `class FairMQProgOptions;` into the actual include to avoid users having incomplete types ?

**Comment by Barthelemy** [comment]
@awegrzyn

**Comment by rbx** [comment]
yes. #745.

**Comment by rbx** [comment]
The fix is now merged.
