### ISSUE TITLE
Move FairLink tasks to FairRoot

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#753]
I have two tasks in PandaRoot which are very usefull if one is working with FairLinks:

- PndPrintFairLinks: Prints all FairLinks stored in the given branches of a tree
- PndMCTruthMatch: Prints the MCTrack to any object in a given branch if a FairLink to the MCTrack exists

In my opinion these methods should be part of FairRoot. If you agree I would move them if you tell me in which folder they should go.

**Comment by MohammadAlTurany** [comment]
I also agree that they should go to FairRoot,  I think they should go to base/event

**Comment by TobiasStockmanns** [comment]
PndPrintFairLinks was merged into FairRoot.
PndMCTruthMatch needs a MCTrack object which is not available in FairRoot. Therefore it stays in PandaRoot
