### ISSUE TITLE
FairRun::GetOutputFile removed breaks backward compatibility

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#771]
FairRun::GetOutputFile() was removed in the dev branch.
This method is used in PandaRoot which therefore crashes and cannot be compiled.

Is there a subsititute for this method?

**Comment by dennisklein** [comment]
I believe this function was replaced by the `FairSink` facility. Try setting a `FairFileSink`.

**Comment by karabowi** [comment]
Dear Tobias,

With the new interface, the FairSink, FairRoot may store the output data using other means than the output file (f.e. it may send via FairMQ). Therefore it is not guaranteed that there will even be output file to return.
Thus, the method GetOutputFile is now gone. If you want to store another data, like histograms,
you should create a separate file.

**Comment by TobiasStockmanns** [comment]
We will change PandaRoot accordingly but it would be nice if the interface of a class changes that this change is done in two stages.
First giving a warning that this method will not be available in the future and, just in the second stage, remove it.

**Comment by dennisklein** [comment]
I believe this issue is resolved by reintroducing the removed API as deprecated. Reopen, if it doesn't work or anything is missing.
