### ISSUE TITLE
Problems with pthread in FairRoot (issue moved from GSI Forum)

### ISSUE THREAD

**Issue by MohammadAlTurany** [FairRootGroup/FairRoot#793]
This issue was reported originally on [GSI Forum](https://forum.gsi.de/index.php?t=post&reply_to=22714&rid=0&SQ=fce68b0229469336830d8da30244d99d&).

> Hi everybody,
>
>after successfully configuring the current version of FairSoft on CentOS 7, I tried to install FairRoot. Running cmake resulted in the following error:
>
>CMake Error at cmake/modules/FindGo.cmake:49 (message):
>Go build for go-processor failed!
>Call Stack (most recent call first):
>examples/advanced/GoTutorial/CMakeLists.txt:6 (build_go_package)
>
>
>-- Configuring incomplete, errors occurred!
>I attached the corresponding CMakeError and CMakeOutput logs. The issue seems to be something related to pthread from what I can gather from the logs. pthread is installed and is also found by cmake:
>
>-- Looking for pthread.h
>-- Looking for pthread.h - found
>-- Looking for pthread_create
>-- Looking for pthread_create - not found
>-- Looking for pthread_create in pthreads
>-- Looking for pthread_create in pthreads - not found
>-- Looking for pthread_create in pthread
>-- Looking for pthread_create in pthread - found
>-- Found Threads: TRUE 
>
>Did anyone already encounter this issue? Or is running the current version of FairRoot on CentOS 7 and knows how I can get it up and running? 
>Thanks for your help!
>Cheers,
>Benjamin

[CMakeError.log](https://github.com/FairRootGroup/FairRoot/files/2097540/CMakeError.log)
[CMakeOutput.log](https://github.com/FairRootGroup/FairRoot/files/2097541/CMakeOutput.log)

**Comment by dennisklein** [comment]
Looking at the logs, I agree with Mohammad's assessment that this is a problem with the Go installations. Our CMake just finds the go executable in the `PATH` environment variable and later calls `go get` in the two go tutorial directories. This is not related to the pthread detection also performed by CMake.

Can you try the following:

```
FairRoot$ cd examples/advanced/GoTutorial/src/go-processor
FairRoot/examples/advanced/GoTutorial/src/go-processor$ go get
```

**Comment by sbinet** [comment]
FWIW, I tried the following on lxplus7:
```
$> which go
/usr/bin/go

$> go version
go version go1.9.4 linux/amd64

$> go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/afs/cern.ch/user/b/binet/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/binet/go-build482351632=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

and then:
```
$> cd examples/eadvanced/GoTutorial/src/go-processor
$> go get -v
github.com/sbinet-alice/fer (download)
created GOPATH=/afs/cern.ch/user/b/binet/go; see 'go help gopath'
github.com/go-mangos/mangos (download)
github.com/go-zeromq/zmq4 (download)
github.com/pkg/errors (download)
Fetching https://golang.org/x/sync/errgroup?go-get=1
Parsing meta tags from https://golang.org/x/sync/errgroup?go-get=1 (status code 200)
get "golang.org/x/sync/errgroup": found meta tag get.metaImport{Prefix:"golang.org/x/sync", VCS:"git", RepoRoot:"https://go.googlesource.com/sync"} at https://golang.org/x/sync/errgroup?go-get=1
get "golang.org/x/sync/errgroup": verifying non-authoritative meta tag
Fetching https://golang.org/x/sync?go-get=1
Parsing meta tags from https://golang.org/x/sync?go-get=1 (status code 200)
golang.org/x/sync (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
go install: no install location for directory /afs/cern.ch/work/b/binet/alice/fff/install/FairRoot/examples/advanced/GoTutorial/src/go-processor outside GOPATH
	For more details see: 'go help gopath'
```

that's probably the same error that Benjamin is seeing in the original GSI post.

Experimental-programming this (definitely *not* an expert of `CMakeLists.txt`) it seems this is because for some reason, when in `examples/advanced/GoTutorial/CMakeLists.txt`:
```cmake
#set(GOPATH $ENV{GOPATH})
set(GOPATH ${CMAKE_SOURCE_DIR}/examples/advanced/GoTutorial)
set(ENV{GOPATH} "${GOPATH}")

build_go_package(go-processor "${GOPATH}")
build_go_package(go-sink "${GOPATH}")

Install(
  FILES ${GOPATH}/bin/go-processor ${GOPATH}/bin/go-sink
  PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ
  DESTINATION bin
)
```

I guess something's changed in how CMake-3 does thing b/c with the following diff:
```diff
diff --git a/cmake/modules/FindGo.cmake b/cmake/modules/FindGo.cmake
index f564affd7..b16292b97 100644
--- a/cmake/modules/FindGo.cmake
+++ b/cmake/modules/FindGo.cmake
@@ -45,7 +45,7 @@ macro(build_go_package pkg gopath)
   execute_process(COMMAND ${GO_EXECUTABLE} get
                   WORKING_DIRECTORY ${workdir}
                   RESULT_VARIABLE goret)
-  if(NOT "${goret}")
+  if(goret)
     message(FATAL_ERROR "Go build for ${pkg} failed!")
   endif()
 endmacro(build_go_package)
```

I was able to build the whole thing. (and also detect a build failure when, say, the `go-processor` target contained an error.)

Now... my `CMakeList.txt`-foo is very weak.
so perhaps (most probably) there is a better way to tackle this.

**Comment by dennisklein** [comment]
@sbinet Can you confirm this install error also happens, when you set the `GOPATH` as suggested in my listing?

**Comment by sbinet** [comment]
```
FairRoot$ export GOPATH=$FAIRROOTSOURCEDIR/examples/advanced/GoTutorial
```

is what the `FindGo.cmake` file is supposed to do.

**Comment by sbinet** [comment]
so, yes, everything should work, now. (after that patch has been applied, of course :P)

**Comment by dennisklein** [comment]
Just for completeness, I would like to point out, that we also have a build switch for the GoTutorial, with `-DDISABLE_GO=ON` one can switch off building the GoTutorial. In the forum post the original bug reporter mentioned, that he commented out some lines in CMake to make it work for him.

**Comment by dennisklein** [comment]
Thx for the help!
