### ISSUE TITLE
GeoTracks not found via GetObject

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#799]
The FairMCTracks "GeoTracks" are used to store MC information about the flight path of MC Tracks. It is used in the eventdisplay to visualize MCTracks.
In the latest FairRoot version the visualization of the GeoTracks does not work anymore.
The command `FairRootManager::Instance()->GetObject("GeoTracks")` returns `nullptr` even though the object is visible in the TBrowser and can be accessed.

**Comment by dennisklein** [comment]
I can confirm the issue on current `dev` with FairSoft may18.

**Comment by TobiasStockmanns** [comment]
Works for me.
Thank you for the fast fix.
