### ISSUE TITLE
Dev branch won't compile without #include <assert.h>

### ISSUE THREAD

**Issue by rklasen** [FairRootGroup/FairRoot#807]
Hi,

when I checked out the latest dev branch and tried to compile, FairRun.cxx and RairRootManager.cxx could not be built as they were missing an `#include <assert.h>`. Adding this include to `FairRun.h` solved the issue and FairRoot compiles.

This is on Ubuntu 18.04, gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 

Should I open a PR for this?

**Comment by MohammadAlTurany** [comment]
Hi,
Yes, please open a PR.
Thanks
