### ISSUE TITLE
FairLogger.h instructive warnings

### ISSUE THREAD

**Issue by RalfKliemt** [FairRootGroup/FairRoot#814]
The FairLogger.h prints a 'deprecated' warning if the "old" logging style is being used. I suggest adding the respective severity level syntax in the warnings.

Use 'LOG(FATAL) << content;' macro interface instead.
Use 'LOG(ERROR) << content;' macro interface instead.
Use 'LOG(WARNING) << content;' macro interface instead.
Use 'LOG(INFO) << content;' macro interface instead.
Use 'LOG(DEBUG) << content;' macro interface instead.
...

A list of logging statements in the Readme.md would be helpful, as well.

LOG(FATAL) << content << FairLogger::endl;
LOG(ERROR) << content << FairLogger::endl;
LOG(WARNING) << content << FairLogger::endl;
LOG(INFO) << content << FairLogger::endl;
LOG(DEBUG) << content << FairLogger::endl;

Cheers!
  Ralf

**Comment by rbx** [comment]
The logger docs have been moved with the FairMQ repo:
https://github.com/FairRootGroup/FairMQ/blob/master/docs/Logging.md
I will split the base part to the FairLogger repo itself.

> I suggest adding the respective severity level syntax in the warnings
Sure, will do.

**Comment by rbx** [comment]
Btw, you no longer need `FairLogger::endl`. All it does is add a space. Just do `LOG(DEBUG) << content;`

**Comment by RalfKliemt** [comment]
Thanks.

**Comment by rbx** [comment]
solved.
