### ISSUE TITLE
Problem with TGeoTracks branch in simulation file after updating to ROOT 6-14-04

### ISSUE THREAD

**Issue by MohammadAlTurany** [FairRootGroup/FairRoot#828]
**Describe the bug**
When switching on the visualisation in Tutorial4 or Rutherford example the simulation works but the Tree cannot be accessed due to problem  with the TGeoTrack branch.
**To Reproduce**
1.  Use ROOT 6.14.04 from AliBuild or FairSoft
2. Run the examples 
3. Try to access the tree 

**System information (please complete the following information):**
 - OS:  MacOS 10.13.6 and Ubuntu 16.04.5
 - Compiler:  GCC 7.3 and  Clang 3.5
 - Environment: FairSoft or aliBuild with ROOT 6.14.04

**Comment by olantwin** [comment]
I can also reproduce this issue on Fedora 28 with aliBuild and GCC 8.1.1.

**Comment by MohammadAlTurany** [comment]
It seems like a ROOT problem! if I take the files generated with root 6-14-4 and read them with ROOT 6-12-06 all works ok without any problem!!

**Comment by dennisklein** [comment]
I remember some news about new compression algorithms in 6.14, could it be related?

**Comment by olantwin** [comment]
I don't think so. 6.14/04 reverts the change of default compression algorithm, and afaik 6.12/06 supports the new algorithm as well.

**Comment by MohammadAlTurany** [comment]
Hi,
I could reproduce the error with two simple macros, directly in ROOT without anything from FairRoot.

[create_tree.C](https://github.com/FairRootGroup/FairRoot/files/2469689/create_tree.C.txt)
[read_tree.C](https://github.com/FairRootGroup/FairRoot/files/2469690/read_tree.C.txt)

This works without any problem with ROOT 6.12.6 and crashes with ROOT 6.14.4

I will make a bug report to ROOT team.

**Comment by MohammadAlTurany** [comment]
Ticket is opened in ROOT Jira: 

https://sft.its.cern.ch/jira/browse/ROOT-9725

**Comment by MohammadAlTurany** [comment]
Problem is solved see  https://sft.its.cern.ch/jira/browse/ROOT-9725
