### ISSUE TITLE
Segmentation violation in FairGeanePro

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#860]
**Describe the bug**
When running the GEANE propagation in PandaRoot I get on OSX 10.14.1 first an error message:

Error in ERTRAK : Inconsistent character options. Tracking stops now

and after that a segmentation error with a backtrace listet later. On our Linux machines this problem does not show up. Something very strange is that this error vanishes if I introduce `std::cout << "Test" << std::endl;` into the `Bool_t FairGeanePro::Propagate(Int_t PDG)` method right before the call to `gMC3->Ertrak(x1,p1,x2,p2,GeantCode, fPropOption.Data());` at line 359

**To Reproduce**
Run PandaRoot macros: macros/master/sim_complete.C digi_complete.C reco_complete.C

**Expected behavior**
Propagation of particles without segmentation error

**Logs / Screenshots**
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[<unknown binary>] (no debug info)
[/Users/tstockmanns/PandaSoftware/FairRoot/dev/install/lib/libGeane.18.dylib] FairGeanePro::Propagate(int) /Users/tstockmanns/PandaSoftware/FairRoot/dev/source/geane/FairGeanePro.cxx:360
[/Users/tstockmanns/PandaSoftware/FairRoot/dev/install/lib/libGeane.18.dylib] FairGeanePro::Propagate(FairTrackParH*, FairTrackParH*, int) /Users/tstockmanns/PandaSoftware/FairRoot/dev/source/geane/FairGeanePro.cxx:200
[/Users/tstockmanns/PandaSoftware/PandaRoot/dev/build/lib/libRecoTasks.0.dylib] PndRecoKalmanFit::Fit(PndTrack*, int) /Users/tstockmanns/PandaSoftware/PandaRoot/dev/source/tracking/GenfitTools/recotasks/PndRecoKalmanFit.cxx:259
[/Users/tstockmanns/PandaSoftware/PandaRoot/dev/build/lib/libRecoTasks.0.dylib] PndRecoKalmanTask::Exec(char const*) /Users/tstockmanns/PandaSoftware/PandaRoot/dev/source/tracking/GenfitTools/recotasks/PndRecoKalmanTask.cxx:246
[/Users/tstockmanns/PandaSoftware/FairRoot/dev/install/lib/libBase.18.dylib] FairTask::ExecuteTasks(char const*) /Users/tstockmanns/PandaSoftware/FairRoot/dev/source/base/steer/FairTask.cxx:210
[/Users/tstockmanns/PandaSoftware/FairRoot/dev/install/lib/libBase.18.dylib] FairTask::ExecuteTasks(char const*) /Users/tstockmanns/PandaSoftware/FairRoot/dev/source/base/steer/FairTask.cxx:214
[/Users/tstockmanns/PandaSoftware/FairRoot/dev/install/lib/libBase.18.dylib] FairTask::ExecuteTask(char const*) /Users/tstockmanns/PandaSoftware/FairRoot/dev/source/base/steer/FairTask.cxx:175
[/Users/tstockmanns/PandaSoftware/FairRoot/dev/install/lib/libBase.18.dylib] FairRunAna::Run(int, int) /Users/tstockmanns/PandaSoftware/FairRoot/dev/source/base/steer/FairRunAna.cxx:372
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] cling::Interpreter::RunFunction(clang::FunctionDecl const*, cling::Value*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] cling::Interpreter::EvaluateInternal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] cling::MetaSema::actOnxCommand(llvm::StringRef, llvm::StringRef, cling::Value*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] cling::MetaParser::isXCommand(cling::MetaSema::ActionResult&, cling::Value*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] cling::MetaParser::isCommand(cling::MetaSema::ActionResult&, cling::Value*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCling.so] TCling::ProcessLineSynch(char const*, TInterpreter::EErrorCode*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libCore.6.12.so] TApplication::ExecuteFile(char const*, int*, bool) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libRint.6.12.so] TRint::ProcessLineNr(char const*, char const*, int*) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/lib/root/libRint.6.12.so] TRint::Run(bool) (no debug info)
[/Users/tstockmanns/PandaSoftware/FairSoft/dev/build/bin/root.exe] main (no debug info)
[/usr/lib/system/libdyld.dylib] start (no debug info)

**System information (please complete the following information):**
 - OS: 10.14.1
 - Compiler: [e.g. GCC 8.1, Clang 3.5]
 - Environment: FairRoot "v18.0.0-62-g3b42af0de" "Tue Dec 11 12:48:06 2018 +0100"

**Additional context**

See [github markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) on how to format inline codes examples and logs.

**Comment by MohammadAlTurany** [comment]
Hi Tobias,
Just to update you about the status.  It still not solved!

I was able to reproduce this error by updating from macOS 10.13.6 to 10.14.2. FairSoft was already compiled with 10.13.6. This create exactly the behaviour you described here. Unfortunately debuting this is not possible because the lldb complain that debug map object files has changed since the executables where linked. 

If you recompile FairSoft  from scratch you still get errors from the ERTRAK (Inconsistent character option) but no crashes, adding a "COUT" does not change anything it simply print it  out and continue. 

Now I am trying to understand why the options get corrupted when transferred from the C++ world to Fortran!!

**Comment by MohammadAlTurany** [comment]
I could solve the problem and created PR in geant3-vmc project: https://github.com/vmc-project/geant3/pull/23

**Comment by TobiasStockmanns** [comment]
Fixed by Radek`s patch for Geant3
