### ISSUE TITLE
Timeout issues upon running make test in the build directory

### ISSUE THREAD

**Issue by rutterj** [FairRootGroup/FairRoot#861]
I have compiled FairSoft and FairRoot without issue, but upon trying to run a make test, there are two tests that fail with the following output:

The following tests FAILED:
	 35 - run_digi_timebased_TGeant3 (Timeout)
	 41 - run_digi_timebased_TGeant4 (Timeout)
Errors while running CTest
make: *** [test] Error 8

This is on a CentOS 7 machine. Not sure where to go from here. Suggestions?

**Comment by MohammadAlTurany** [comment]
could you run the dart.sh in the source directory of FairRoot so that we get the build results and test errors on the [Dashboard](https://cdash.gsi.de/index.php?project=FairRoot)

**Comment by rutterj** [comment]
> could you run the dart.sh in the source directory of FairRoot so that we get the build results and test errors on the [Dashboard](https://cdash.gsi.de/index.php?project=FairRoot)

I'm attempting to pass two arguments to dart.sh by doing the following:
export BUILDDIR=~/fair_install/FairRoot/build
export SIMPATH=~/fair_install/FairSoftInst
Then running:
./Dart.sh SIMPATH BUILDDIR
Which yields the following result:
-- Error -- This ctest model is not supported.
-- Error -- Possible arguments are Nightly, Experimental, Continuous or Profile.

What is the proper way to use Dart.sh?

**Comment by MohammadAlTurany** [comment]
You need to create a text file with: (e.g. myconfig)

 !/bin/bash                                                      
 export LINUX_FLAVOUR="your linux flavour"                        
 export FAIRSOFT_VERSION="version of FairSoft"                  
 export SIMPATH="path to your FairSoft version"                   
 export GIT_BRANCH="master , dev, ..."                               
 export BUILDDIR="dir where the build files go"        
 export SOURCEDIR="location of the FairRoot sources"

Then you call:

./Dart.sh  Experimental  myconfig

**Comment by rutterj** [comment]
Here is the output of Dart.sh
``````
************************
Tue Jan  8 08:28:52 CST 2019
LABEL:  CentOS 7-x86_64-gcc4.8.5-FairRoot_master-FairSoft_
SITE:  UWO6981L0
Model:  Experimental
Nr. of processes:  4
************************
CMake Error: Cannot find file: /FairBase_test.cmake
``````

**Comment by MohammadAlTurany** [comment]
did you run it in the FairRoot source directory?

**Comment by rutterj** [comment]
Yes, it was run within the FairRoot directory.

**Comment by MohammadAlTurany** [comment]
The file "[FairBase_test.cmake](https://github.com/FairRootGroup/FairRoot/blob/master/FairBase_test.cmake)" is delivered by FairRoot and is in main directory. 

Could you check that it is there? and that you export the right directory in "SOURCEDIR".

**Comment by rutterj** [comment]
I defined one of the directories wrong in the export file. Below is the Dart.sh output:

````
Run dashboard with model Experimental
   Source directory: /root/fair_install/FairRoot
   Build directory: /root/fair_install/FairRoot/build
   Reading ctest configuration file: /root/fair_install/FairRoot/build/CTestConfig.cmake
   Site: UWO6981L0
   Build name: CentOS 7-x86_64-gcc4.8.5-FairRoot_master-FairSoft_
   Use Experimental tag: 20190108-1748
Configure project
   Each . represents 1024 bytes of output
    ...... Size of output: 5K
Build project
   Each symbol represents 1024 bytes of output.
   '!' represents an error and '*' a warning.
    ............................... Size of output: 30K
   0 Compiler errors
   0 Compiler warnings
Test project /root/fair_install/FairRoot/build
      Start 12: run_tutorial2
      Start 26: pixel_sim_TGeant3
      Start 38: run_sim_TGeant4
      Start 32: run_sim_TGeant3
 1/48 Test #12: run_tutorial2 ....................   Passed    1.64 sec
      Start 13: create_digis
 2/48 Test #13: create_digis .....................   Passed    1.47 sec
      Start 14: read_digis
 3/48 Test #14: read_digis .......................   Passed    1.44 sec
      Start 15: run_bg
 4/48 Test #15: run_bg ...........................   Passed    1.55 sec
      Start 16: run_sg
 5/48 Test #32: run_sim_TGeant3 ..................   Passed    6.17 sec
      Start 35: run_digi_timebased_TGeant3
 6/48 Test #38: run_sim_TGeant4 ..................   Passed    6.96 sec
      Start 41: run_digi_timebased_TGeant4
 7/48 Test #16: run_sg ...........................   Passed    1.62 sec
      Start 21: run_tutorial4_TGeant4
 8/48 Test #26: pixel_sim_TGeant3 ................   Passed    9.72 sec
      Start 27: pixel_digi_TGeant3
 9/48 Test #21: run_tutorial4_TGeant4 ............   Passed    5.73 sec
      Start 24: MQ.ex-serialization1
10/48 Test #27: pixel_digi_TGeant3 ...............   Passed    3.54 sec
      Start 28: pixel_dbin_TGeant3
11/48 Test #24: MQ.ex-serialization1 .............   Passed    5.03 sec
      Start 19: run_tutorial4_TGeant3
12/48 Test #28: pixel_dbin_TGeant3 ...............   Passed    5.04 sec
      Start 39: run_digi_TGeant4
13/48 Test #19: run_tutorial4_TGeant3 ............   Passed    3.33 sec
      Start 17: run_sg1
14/48 Test #39: run_digi_TGeant4 .................   Passed    3.33 sec
      Start 33: run_digi_TGeant3
15/48 Test #17: run_sg1 ..........................   Passed    3.68 sec
      Start 29: pixel_simulation
16/48 Test #33: run_digi_TGeant3 .................   Passed    3.68 sec
      Start 11: run_tutorial1_urqmd_TGeant4
17/48 Test #11: run_tutorial1_urqmd_TGeant4 ......   Passed    9.26 sec
      Start  9: run_tutorial1_pythia8_TGeant4
18/48 Test #29: pixel_simulation .................   Passed   12.54 sec
      Start  4: run_tutorial1_pythia8_TGeant3
19/48 Test  #9: run_tutorial1_pythia8_TGeant4 ....   Passed    6.88 sec
      Start 37: run_DiRePr_TGeant3
20/48 Test  #4: run_tutorial1_pythia8_TGeant3 ....   Passed    7.29 sec
      Start  7: run_tutorial1_TGeant4
21/48 Test #37: run_DiRePr_TGeant3 ...............   Passed    6.81 sec
      Start 10: run_tutorial1_mesh_TGeant4
22/48 Test  #7: run_tutorial1_TGeant4 ............   Passed    8.60 sec
      Start 43: run_DiRePr_TGeant4
23/48 Test #10: run_tutorial1_mesh_TGeant4 .......   Passed    5.47 sec
      Start  8: run_tutorial1_pythia6_TGeant4
24/48 Test #43: run_DiRePr_TGeant4 ...............   Passed    5.72 sec
      Start  6: run_tutorial1_urqmd_TGeant3
25/48 Test  #6: run_tutorial1_urqmd_TGeant3 ......   Passed    5.25 sec
      Start 46: run_rutherford_TGeant4
26/48 Test #35: run_digi_timebased_TGeant3 .......***Timeout  61.50 sec
      Start 47: run_rad_TGeant4
27/48 Test  #8: run_tutorial1_pythia6_TGeant4 ....   Passed   23.34 sec
      Start  2: run_tutorial1_TGeant3
28/48 Test #46: run_rutherford_TGeant4 ...........   Passed   12.52 sec
      Start  5: run_tutorial1_mesh_TGeant3
29/48 Test #41: run_digi_timebased_TGeant4 .......***Timeout  70.58 sec
      Start  3: run_tutorial1_pythia6_TGeant3
30/48 Test #47: run_rad_TGeant4 ..................   Passed   10.32 sec
      Start 25: MQ.ex-serialization2
31/48 Test  #2: run_tutorial1_TGeant3 ............   Passed   10.18 sec
      Start 40: run_reco_TGeant4
32/48 Test  #5: run_tutorial1_mesh_TGeant3 .......   Passed   10.14 sec
      Start 34: run_reco_TGeant3
33/48 Test #34: run_reco_TGeant3 .................   Passed    1.53 sec
      Start 45: run_rad_TGeant3
34/48 Test #40: run_reco_TGeant4 .................   Passed    1.71 sec
      Start 22: run_reco_tut4_TGeant4
35/48 Test #25: MQ.ex-serialization2 .............   Passed    2.24 sec
      Start 42: run_reco_timebased_TGeant4
36/48 Test  #3: run_tutorial1_pythia6_TGeant3 ....   Passed    2.71 sec
      Start 44: run_rutherford_TGeant3
37/48 Test #45: run_rad_TGeant3 ..................   Passed    1.74 sec
      Start 20: run_reco_tut4_TGeant3
38/48 Test #22: run_reco_tut4_TGeant4 ............   Passed    1.58 sec
      Start 18: create_digis_mixed
39/48 Test #42: run_reco_timebased_TGeant4 .......   Passed    1.45 sec
      Start 36: run_reco_timebased_TGeant3
40/48 Test #44: run_rutherford_TGeant3 ...........   Passed    1.49 sec
      Start 48: unpack_mbs
41/48 Test #20: run_reco_tut4_TGeant3 ............   Passed    1.49 sec
      Start  1: load_all_libs
42/48 Test #18: create_digis_mixed ...............   Passed    1.51 sec
43/48 Test #36: run_reco_timebased_TGeant3 .......   Passed    1.37 sec
44/48 Test  #1: load_all_libs ....................   Passed    0.48 sec
45/48 Test #48: unpack_mbs .......................   Passed    1.27 sec
      Start 30: pixel_static
46/48 Test #30: pixel_static .....................   Passed    5.45 sec
      Start 31: pixalt_static
47/48 Test #31: pixalt_static ....................   Passed    3.87 sec
      Start 23: MQ.ex-parameterss
48/48 Test #23: MQ.ex-parameterss ................   Passed    0.60 sec

96% tests passed, 2 tests failed out of 48

Total Test time (real) = 103.24 sec

The following tests FAILED:
	 35 - run_digi_timebased_TGeant3 (Timeout)
	 41 - run_digi_timebased_TGeant4 (Timeout)
Submit files (using https)
   Using HTTP submit method
   Drop site:https://cdash.gsi.de/submit.php?project=FairRoot
   Uploaded: /root/fair_install/FairRoot/build/Testing/20190108-1748/Build.xml
   Uploaded: /root/fair_install/FairRoot/build/Testing/20190108-1748/Configure.xml
   Uploaded: /root/fair_install/FairRoot/build/Testing/20190108-1748/Test.xml
   Submission successful
CMake Error at /root/fair_install/FairRoot/FairBase_test.cmake:90 (Message):
  Some tests failed.

````

**Comment by MohammadAlTurany** [comment]
Unfortunately something went wrong with the submission to the Cdash server,  the output of the  failing tests cannot be parsed (https://cdash.gsi.de/viewTest.php?onlyfailed&buildid=195744).

So [lease try to run the Dart.sh again changing the build directory to have a clean directory or you can try to run the tests manually from the example directory, the failing tests are in **_build/examples/advanced/Tutorial3/macro_**, First you have to run "run_sim.sh" and then run_digi_timebased.sh

**Comment by dennisklein** [comment]
There might be even another way to get the logs: After running `make test` there should be a file `Testing/Temporary/LastTest.log` in your build directory. @rutterj If you can find this file, could you please attach it here?

**Comment by rutterj** [comment]
I have the log the only problem is that it's ~250mb and compresses down to 50mb. Any attempt to open it in nano or a text editor crashes the program. I've instead uploaded to google drive and made a sharable link:

https://drive.google.com/file/d/10sCbbYCCCRM3lHVzZ2nqy8Ye0AlaXwDa/view?usp=sharing

**Comment by rutterj** [comment]
I recompiled cling just in case there was an issue there, but I still get the same error as before. Not really sure what to do. I've tested this on another system and get identical errors. 

I'm following install instructions from here: https://github.com/FairRootGroup/FairRoot

**Comment by MohammadAlTurany** [comment]
From the output it seems that the tests runs ok, however the binary and the C++ dump means that ROOT has a problem on exiting the test. Could you please try to switch to the dev branch and see if the problem still exist we already have corrected some issues with double deletion which could be related to this

**Comment by MohammadAlTurany** [comment]
Ok, we need to reproduce this problem can you  tell us which system and which compiler  you are using?

**Comment by rutterj** [comment]
I'm running on a fresh CentOS 7 install, and doing exactly the following, in order:

Install centos 7 and open terminal
give myself root access

Pass the following commands:
yum update
yum groupinstall 'Development Tools'

Then, I begin installation of FairSoft:

````
mkdir ~/fair_install
cd ~/fair_install
git clone -b master https://github.com/FairRootGroup/FairSoft.git
cd FairSoft
./configure.sh

````
I then go through the prompts and have the following options selected:
````
gcc
Yes, Debug Info
optimize no
build_MQOnly=no
geant4_download_install data_automatic=yes
build root6=yes
build python=no
install sim=yes
SIMPATH_Install=/root/fair_install/FairSoftInst
platform=linux
````
Then I open up my bash profile
````
nano ~/.bash_profile
````
and set my PATH environmental variable to 
'PATH=/root/fair_install/FairSoftInst/bin:$PATH`
which it says to do once FairSoft has been compiled, because of the version of CMAKE that it installed.
Then, I reload my bash profile
' source ~/.bash_profile`
Next I do the following:
````
export SIMPATH=~/fair_install/FairSoftInst

cd ~/fair_install
git clone -b master https://github.com/FairRootGroup/FairRoot.git
cd FairRoot
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="~/fair_install/FairRootInst" ..
make
make install
````
After that I do a 'make test' inside the build directory, and that's when errors start to occur.

**Comment by MohammadAlTurany** [comment]
Hi,
We managed to reproduce this problem on CentOs 7 and gcc 4.8.5. The Problem is in the order of deleting the static objects on ROOT exit. We will update the FairLogger in FairSoft and this should solve the problem.

**Comment by rutterj** [comment]
Thank you for all your help. Should I download and try the install again?

**Comment by rbx** [comment]
Yes, the relevant changes are in the dev branch of FairSoft, so make sure to use that branch.

**Comment by MohammadAlTurany** [comment]
And FairRoot dev.

**Comment by rutterj** [comment]
I was able to successfully compile and run "make test' in the build directory without errors. Thank you again for your help with this issue.
