### ISSUE TITLE
FairHit taking references instead of const references

### ISSUE THREAD

**Issue by BSali** [FairRootGroup/FairRoot#891]
Ahoi, this is not really a bug nor a feature request, more an inconvenience, but at least very easy to fix. ^^

The FairHit constructor takes a reference each to a position and a direction TVector3, instead of const references. This prevents the user from calling the FairHit constructor with rvalues, e.g.:

` FairHit(anyInt, TVector3{1.0, 1.0, 1.0}, TVector3{0.,0.,0.}, anotherInt);`

This seems odd as there is no reason why it should take non-const references.

**Comment by dennisklein** [comment]
Do you want to propose a PR with a fix?

We should think a moment if there are any consequences for the ROOT I/O (when changing the args to `const&` or adding another constructor which takes `const&`s).

**Comment by dennisklein** [comment]
Should be fixed by #949, reopen otherwise.
