### ISSUE TITLE
Is FAIRROOT_MODULAR_BUILD active?

### ISSUE THREAD

**Issue by siscia** [FairRootGroup/FairRoot#900]
Hi,

I am trying to build FairRoot using the FAIRROOT_MODULAR_BUILD option, but it seems to don't be active.

https://github.com/FairRootGroup/FairRoot/blob/master/CMakeLists.txt#L124
https://github.com/FairRootGroup/FairRoot/blob/master/CMakeLists.txt#L230

Is the readme just outdated?

**Comment by dennisklein** [comment]
Yes, looks like the `v18.2.0` release removed `FAIRROOT_MODULAR_BUILD`. The docs are outdated in that regard, thx for pointing that out. We always search via the standard cmake [search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure) now (Be aware, it depends also on your CMake version, make sure to check the docs for your version). In addition, you can set prioritized search hints via `$SIMPATH`, `-D<UPPERCASEPKGNAME>_ROOT`, `$<UPPERCASEPKGNAME>_ROOT`.
