### ISSUE TITLE
FairDetector: EndOfEvent and FinishEvent

### ISSUE THREAD

**Issue by vfriese** [FairRootGroup/FairRoot#913]
FairDetector provides two virtual methods for end-of-event action: void EndOfEvent() and void FinishEvent(). Both are called from FairMCApplication::FinishEvent().

Is there a reason to have both methods, or is one of them legacy? If the latter is true, I propose to remove it (no backward compatibility, of course).

I would appreciate if the end-of-event method of the detectors (whichever name) could be called before the FinishEvent() methods of the tasks. Not important, just cosmetics. But the Exec of the tasks is also called after the detector action in each event, so the same sequence would be logical also for the end-of-event action.

**Comment by MohammadAlTurany** [comment]
The difference between **"FinishEvent"** and **"EndOfEvent"** is that **"Finish"** event is called before filling the tree (Call to **FairRootManager::Fill()**) and **"EndOFEvent"**  after.  At the time we implemented this, the idea was to use the one before the fill and after exec to make some event global calculations (e.g. total energy deposition per crystal in Ecal) where the one after fill can be used to clear (delete) the containers.

**Comment by vfriese** [comment]
Thanks for the clarification! Would be nice to add a respective documentation to the code, just in case someone else will have the same question.
