### ISSUE TITLE
NULL protection missing

### ISSUE THREAD

**Issue by RalfKliemt** [FairRootGroup/FairRoot#955]
https://github.com/FairRootGroup/FairRoot/blob/e6cd7da7d60d0983cd0c1014a611376a1e8fe0c4/base/event/FairMultiLinkedData_Interface.h#L37

not urgent

**Comment by dennisklein** [comment]
Looks like a candidate for a `std::unique_ptr`.

**Comment by dennisklein** [comment]
We believe it is fixed in the `dev` branch, but nobody has tested it yet. Reopen, if you encounter any problems.
