### ISSUE TITLE
FairRoot and PCL library with C++14

### ISSUE THREAD

**Issue by Yassid** [FairRootGroup/FairRoot#961]
**Is your feature request related to a problem? Please describe.**
I have been always using PCL 1.8.0 with FairRoot in my ATTPCROOTv2 project without problem (https://github.com/ATTPC/ATTPCROOTv2/). The newest PCL library (10) has enabled C++14 by default. I added the corresponding compilation flags in the CMakeLists but the generation of the dictionary makes the compilation fail:

`[ 21%] Generating G__ATTPCRecoDict.cxx, G__ATTPCRecoDict_rdict.pcm, ../lib/libATTPCReco.rootmap
[ 30%] Built target AtGen
[ 36%] Built target AtTpc
In file included from input_line_12:2402:
In file included from /mnt/simulations/attpcroot/fair_install_2020/pcl_1.9.1_inst/include/pcl-1.10/pcl/io/io.h:42:
In file included from /mnt/simulations/attpcroot/fair_install_2020/pcl_1.9.1_inst/include/pcl-1.10/pcl/common/io.h:46:
In file included from /mnt/simulations/attpcroot/fair_install_2020/pcl_1.9.1_inst/include/pcl-1.10/pcl/pcl_base.h:46:
In file included from /mnt/simulations/attpcroot/fair_install_2020/pcl_1.9.1_inst/include/pcl-1.10/pcl/pcl_macros.h:77:
/mnt/simulations/attpcroot/fair_install_2020/pcl_1.9.1_inst/include/pcl-1.10/pcl/pcl_config.h:7:4: error: PCL requires C++14 or above
  #error PCL requires C++14 or above
`

If I disable the generation of the dictionary
`Set(LINKDEF ATTPCRecoLinkDef.h)`
for those libraries that use PCL everything compiles.

**Describe the solution you'd like**
It would be convenient to have a way to select between C++11, C++14, C++17...
Do I have to recompile everything (Fairsoft and Fairroot) with C++14? If so, how do enable that? Is this a problem of the dictionary generation only? 

**Describe alternatives you've considered**
Getting rid of PCL :)

**Additional context**

**Comment by dennisklein** [comment]
You should be able to switch the C++ language level with `-DCMAKE_CXX_STANDARD=14` passed to the cmake command when configuring FairRoot. Let me know if this does not work (and how it fails). Recompiling FairSoft is probably not necessary.

**Comment by Yassid** [comment]
Thanks for the quick reply. The CMake command did not work but I was able to force it with 
`set(CMAKE_CXX_FLAGS -std=c++14)`
This did not solve the problem though. I would like to add that, I am able to compile and run a stand-alone program with PCL and ROOT, without generating the library. 
Also, even if the LinkDef of the corresponding ATTPCROOT library is empty, the compilation fails.

**Comment by dennisklein** [comment]
> The CMake command did not work

How did it not work? No effect?

> but I was able to force it with `set(CMAKE_CXX_FLAGS -std=c++14)`

We should try to avoid setting flags directly that are abstracted by CMake nowadays. I know that - depending on the FairSoft/FairRoot version you are using - we might still do something like this ourselves but my intention is to find the proper fix for your use case. FairSoft itself was never configured for a higher language level than C++11 so far, but it is certainly possible.

To share with you some context: The Alice experiment is using FairRoot with C++14 and 17 enabled since a long time successfully, so in principle we just need to sort out the right config (possibly also compile ROOT with C++14 in your case) for FairRoot and FairSoft - Alice however is not using FairSoft but they have their own package management and distro (https://github.com/alisw/alidist) all tuned for C++17.

In order to assist you further, I would need to know the exact versions of
* FairSoft
* FairRoot
* ATTPCROOTv2

you are using (if you refer to some git branch, please include the exact git commit hash since branches tend to be moving targets).

**Comment by Yassid** [comment]
Thank you very much again for the support.

I normally check the flags after CMake is done and I still had --std=c++11. In any case, I fully agree about avoiding "hardcoded" flags.

I am using FairSoft may18 and FairRoot v18.0.0, both master branches. and the develop branch of ATTPCROOTv2 (the default one).

Is there an "easy" way to let the FairSoft configure know that i want to compile ROOT with C++14?

**Comment by dennisklein** [comment]
> Is there an "easy" way to let the FairSoft configure know that i want to compile ROOT with C++14?

Probably not, I need to investigate this, will get back to you early next week.

On a side note, if you want, check out our `dev` branch of FairSoft. We are in the process of migrating FairSoft to the more sophisticated Spack package management. The first release will happen within the next few weeks.

**Comment by dennisklein** [comment]
> >  Is there an "easy" way to let the FairSoft configure know that i want to compile ROOT with C++14?

> Probably not, I need to investigate this, will get back to you early next week.

@fuhlig1 Do you see a chance to easily compile legacy FairSoft with C++14?

**Comment by fuhlig1** [comment]
I have prepared a patch which should do the trick but I want to test it before I send it around.

**Comment by Yassid** [comment]
Awesome, let me know how I can help. For the moment I have compiled everything on Debian Buster wand C+11 (previous tests were done with Jessie).

**Comment by fuhlig1** [comment]
@Yassid I have prepared the patch which can be applied for jun19 releases. In my test all packages got the correct compile flags but I did not run any tests. Please try and report if it works.

[c++14.patch.txt](https://github.com/FairRootGroup/FairRoot/files/4592904/c%2B%2B14.patch.txt)

**Comment by dennisklein** [comment]
The latest FairSoft release `nov20` [requires and enforces a minimum of C++14](https://github.com/FairRootGroup/FairSoft/blob/nov20_patches/cmake/legacy.cmake#L40). The upcoming `mar21` release bumps the minimum further to C++17.

FairRoot `v18.4.3` and later no longer check for the `-std` arg in `CXX_FLAGS`. So,
* if you work with a standard FairSoft installation, just `export SIMPATH=/path/to/fairsoft/nov20/or/mar21` and FairRoot will pick up the C++14/17 from the contained `fairsoft-config` script.
* If you work without FairSoft, you may control the CXX language level now via `-DCMAKE_CXX_STANDARD=14` when configuring FairRoot.
