### ISSUE TITLE
Annoying warnings from FairModule

### ISSUE THREAD

**Issue by fuhlig1** [FairRootGroup/FairRoot#965]
With v18.4 the following warning  was implemented.

```
[root.exe][12:40:19][WARN][FairModule.cxx:567:IsSensitive] Implement IsSensitive in the detector class which inherits from FairModule
[root.exe][12:40:19][WARN][FairModule.cxx:568:IsSensitive] For now calling the obsolete function CheckIfSensitive

```

This warning is printed for each call which adds an enormous amount of annoying output. Even if the problem is easy to fix on the user side by adding the new function it makes it impossible to use FairRoot v18.2 and v18.4 with the same user code or one has to introduce ifdef statements on the user side.  The new function was only introduced with v18.4. 

To reproduce simply compile CbmRoot using the FairRoot RC_v18.4 branch and run the transport macro. 

I would propose to introduce a compiler warning that the function CheckIfSensitive is deprecated with v18.4 and will disappear with the next FairRoot version and remove the runtime warning. This would allow the user to use FairRoot v18.2 and v18.4 without the annoying runtime warnings. When switching to v18.4 without the need to still use v18.2 the user code can be fixed.
There should be at least one FairRoot version where it is possible to use the old and the new feature at the same time. Otherwise it becomes complicated for the user.

**Comment by dennisklein** [comment]
Resolved by #967. Reopen otherwise.
