### ISSUE TITLE
Crash when using FairMonitor

### ISSUE THREAD

**Issue by fuhlig1** [FairRootGroup/FairRoot#966]
When running one of the tests of CbmRoot with FAirRoot v18.4 I run into the following error

```
[/opt/fairroot/v18.4.0_fairsoft-jun19p1/lib/libBase.18.4.0.dylib] FairRootFileSink::Write(char const*, int, int) /opt/fairroot/source/RC_v18.4/base/sink/FairRootFileSink.cxx:348
[/opt/fairroot/v18.4.0_fairsoft-jun19p1/lib/libBase.18.4.0.dylib] FairRootManager::Write(char const*, int, int) /opt/fairroot/source/RC_v18.4/base/steer/FairRootManager.cxx:0
[/opt/fairroot/v18.4.0_fairsoft-jun19p1/lib/libBase.18.4.0.dylib] FairRunOnline::Run(int, int) /opt/fairroot/source/RC_v18.4/base/steer/FairRunOnline.cxx:338
```

The test creates a FairRunOnline instance, defines in- and output, add a task, initializes and then run for some events.

Doing some debug of the problem I could locate the problem in the following function

`
FairMonitor::GetMonitor()->StoreHistograms(fRootFile);
`
The call of

`
 fCanvas->Write();
`

in this function invalidates the file pointer. The underlying problem is that the TCanvas isn't created in the function Draw() of FairMonitor which is called in the function StoreHistograms before calling Canvas->Write().
In my test the function Draw() is left before properly creating the TCanvas because the the "FairTaskList" isn't found in the ListOfBrowsables. I have no clue why our TaskList isn't in there since it is properly created. This can be checked in a root session executing the following commands.
```
root [0] FairRunOnline* run = new FairRunOnline();
[INFO] FairRunOnline constructed at 0x7fceea6f0080
root [1] run->GetMainTask()->GetName()
(const char *) "FairTaskList"
```

There are several ways to solve the issue.

1.
   Switch off the usage of the FairMonitor in my test

2.
   Call fCanvas->Write() only if fCanvas exist.
      if (fCanvas) fCanvas->Write();

3.  Find out why the the FairTaskList is not in the list of browsables and

**Comment by kresan** [comment]
@fuhlig1, I think we need to manually add fTask to the ROOT list of browsables in the constructor of FairRun. Otherwise I do not see how it enters there. Do you agree?

**Comment by fuhlig1** [comment]
@kresan, I also thought about this. This is done already in FairMCApplication when running tasks after the MC simulation. I am only wondering what happened between 18.2 and 18.4 since the macro was working before. Either the task list was in the list of browsables or something else has changed. 
If adding it in the constructor of FairRun works I can't say since for a simulation run it is added in FairMCApplication. With this setup you would add it two times.

**Comment by kresan** [comment]
then it should be not in FairRun but in FairRunOnline, to avoid overlap with FairMCApplication

**Comment by fuhlig1** [comment]
This would probably solve my problem but what about FairRunAna?

**Comment by kresan** [comment]
Do we actually have 2 times task list for simulation? Once in FairRun and once in FairMCApplication?

**Comment by kresan** [comment]
fTask of FairRun is added to tasks of FairMCApplication, which are made browsable. Instead of this we can make fTask in FairRun browsable, once for all cases, and skip it in FairMCApplication

**Comment by fuhlig1** [comment]
Right. We can do this and actually we should fix it but I am not sure if we should do it for the release. This is a larger change which we should test carefully.

**Comment by karabowi** [comment]
I would also be careful with adding the list to gROOT. I would go with the second Florian's option, to protect the writing of fCanvas with check if it exists.

**Comment by karabowi** [comment]
The fTask list is added to browsables explicitly in FairRunAna::Init() line 195 and in the constructor of FairMCApplication line 152. Was there any reason for not adding it in the FairRunOnline?
