### ISSUE TITLE
CMake fails configuring with flatbuffers with shared libraries

### ISSUE THREAD

**Issue by davidrohr** [FairRootGroup/FairRoot#970]
I have been trying to compile FairRoot (4ab2d2b1f0392ad93b92026d70fe049c38665f7d) on Gentoo Linux with a system installation of flatbuffers 1.12.0

It fails during the CMake with the following error:
```
2020-05-06@15:12:00:DEBUG:O2:FairRoot:0: CMake Error at CMakeLists.txt:523 (get_target_property):
2020-05-06@15:12:00:DEBUG:O2:FairRoot:0:   get_target_property() called with non-existent target
2020-05-06@15:12:00:DEBUG:O2:FairRoot:0:   "flatbuffers::flatbuffers".
```

The problem is that my flatbuffers is built with shared libraries and exposes the target flatbuffers::flatbuffers_shared and not flatbuffers::flatbuffers, which is expected by FairMQ/CMakeLists.txt.

The following change made it compile for me, but should be generalized to work in both cases.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ac45e21e7..374f2e496 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -520,7 +520,7 @@ if(PROJECT_PACKAGE_DEPENDENCIES)
       get_target_property(fmt_include fmt::fmt INTERFACE_INCLUDE_DIRECTORIES)
       get_filename_component(prefix ${fmt_include}/.. ABSOLUTE)
     elseif(${dep} STREQUAL Flatbuffers)
-      get_target_property(flatbuffers_include flatbuffers::flatbuffers INTERFACE_INCLUDE_DIRECTORIES)
+      get_target_property(flatbuffers_include flatbuffers::flatbuffers_shared INTERFACE_INCLUDE_DIRECTORIES)
       get_filename_component(prefix ${flatbuffers_include}/.. ABSOLUTE)
     endif()
```

**Comment by dennisklein** [comment]
@ChristianTackeGSI Once we backported the fix from https://github.com/dennisklein/FairRoot/tree/modernize_cmake_phase2, let's remember to revert the pkg level patch https://github.com/FairRootGroup/FairSoft/blob/dev/packages/fairroot/link_against_flatbuffers_shared.patch.

**Comment by ChristianTackeGSI** [comment]
Well, I think, the package level `patch()` will just fail. CI will tell us.
But: Yes, let's remember!

**Comment by dennisklein** [comment]
Fix merged into `dev` and `RC_v18.4.0` branches.
