### ISSUE TITLE
Base should not produce -Wdeprecated on own API

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairRoot#973]
On current [`dev`](https://github.com/FairRootGroup/FairRoot/commit/f6d0b62f3c76fbc997f716e864cde5ef4f13b40f) branch

```
[106/478] Building CXX object base/CMakeFiles/Base.dir/sim/FairModule.cxx.o
../base/sim/FairModule.cxx: In member function ‘virtual Bool_t FairModule::IsSensitive(const string&)’:
../base/sim/FairModule.cxx:563:33: warning: ‘virtual Bool_t FairModule::CheckIfSensitive(std::string)’ is deprecated: The method CheckIfSensitive is deprecated. Implement IsSensitive in the detector classes. [-Wdeprecated-declarations]
  563 |     return CheckIfSensitive(name);
      |                                 ^
In file included from ../base/sim/FairModule.cxx:13:
../base/sim/FairModule.h:99:20: note: declared here
   99 |     virtual Bool_t CheckIfSensitive(std::string name) __attribute__((
      |                    ^~~~~~~~~~~~~~~~
```

**Comment by karabowi** [comment]
This is kind of stupid, I agree. But how to get out of the conundrum?
The virtual CheckIfSensitive(std::string name) function, implemented
in various classes all over the daughter projects, is to be replaced by virtual IsSensitive(const std::string& name).

But before IsSensitive is implemented in daughter projects, the CheckIsSensitive has to be called.
How to organize it? Suppress the warning somehow?

**Comment by dennisklein** [comment]
> Suppress the warning somehow?

Ya, that is probably best:

```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated"

    return CheckIfSensitive(name);

#pragma GCC diagnostic pop
```

Please verify that the above also works on macOS.

**Comment by karabowi** [comment]
The pragmas _do_ suppress the warning on my MAC (OS 10.14.4 + clang 10.0.1).

**Comment by dennisklein** [comment]
Thx, if no one has objections tomorrow in the meeting, let's go for that solution.
