### ISSUE TITLE
Spack dev-build

### ISSUE THREAD

**Issue by TobiasStockmanns** [FairRootGroup/FairRoot#981]
**Describe the bug**
Dev-build to run local code in spack environment fails following description from Dima: https://github.com/kresan/FairSoft/blob/update_readme/README.md#v-development-build

**To Reproduce**
1. I have activated environment jun19 activated but I also worked in dev environment
2. I was running the following command: `spack -C ./config dev-build -j 4 -d ~/PandaSoftware/FairRoot/dev/source fairroot@test+sim+examples ^pcre+jit ^python@2.7.16 ^py-numpy@1.16.5 ^googletest@1.8.1 ^boost@1.68.0 ^fairlogger@1.4.0 \
^dds@2.4 ^fairmq@1.4.3 ^pythia6@428-alice1 ^hepmc@2.06.09 length=CM momentum=GEV ^pythia8@8240 ^geant4@10.05.p01~qt~vecgeom~opengl~x11~motif~data~clhep~threads \
^root@6.16.00+fortran+gdml+memstat+pythia6+pythia8+vc~vdt+python+tmva+xrootd+aqua ^geant3@2-7_fairsoft ^vgm@4-5 ^geant4_vmc@4-0-p1`

**Expected behavior**
Compilation of local FairRoot version

**Logs / Screenshots**
```
spack -C ./config dev-build -j 4 -d ~/PandaSoftware/FairRoot/dev/source fairroot@test+sim+examples ^pcre+jit ^python@2.7.16 ^py-numpy@1.16.5 ^googletest@1.8.1 ^boost@1.68.0 ^fairlogger@1.4.0 \
^dds@2.4 ^fairmq@1.4.3 ^pythia6@428-alice1 ^hepmc@2.06.09 length=CM momentum=GEV ^pythia8@8240 ^geant4@10.05.p01~qt~vecgeom~opengl~x11~motif~data~clhep~threads \
^root@6.16.00+fortran+gdml+memstat+pythia6+pythia8+vc~vdt+python+tmva+xrootd+aqua ^geant3@2-7_fairsoft ^vgm@4-5 ^geant4_vmc@4-0-p1
==> Error: An unsatisfiable version constraint has been detected for spec:

    root@6.16.00+aqua+fortran+gdml+http+memstat+pythia6+pythia8+python+tmva+vc~vdt+xrootd
        ^blas
        ^cmake@3.13.4:+ownlibs
        ^jpeg
        ^libice
            ^pkgconfig@0.9.0:
            ^util-macros
            ^xproto
            ^xtrans
        ^libpng
            ^zlib@1.0.4:
        ^lz4
        ^ncurses
        ^pcre+jit
        ^py-numpy@1.16.5
            ^py-setuptools
                ^python@2.7.16
                    ^gettext
        ^pythia6@428-alice1
        ^pythia8@8240
            ^hepmc@2.06.09 length=CM momentum=GEV
            ^rsync
        ^vc
        ^xrootd
            ^bzip2
                ^diffutils
                    ^libiconv
            ^openssl
                ^perl@5.14.0:
                    ^gdbm
                        ^readline
            ^xz
        ^xxhash


while trying to concretize the partial spec:

    vmc
        ^cmake@3.13.4:+ownlibs


vmc requires root version 6.18.04:, but spec asked for 6.16.00
```

**Comment by ChristianTackeGSI** [comment]
Could you please file the exact same thing as a [FairSoft Issue](https://github.com/FairRootGroup/FairSoft/issues/) and the close here?
I think, this is not a FairRoot issue, but a spack issue.

**Comment by TobiasStockmanns** [comment]
Issue moved to FairSoft
