### ISSUE TITLE
Tutorial4 crashes

### ISSUE THREAD

**Issue by MohammadAlTurany** [FairRootGroup/FairRoot#999]
**Describe the bug**
Tutorial 4 in FairRoot crashes because tit looks for input/output files in anon existing directory (data)
**To Reproduce**
Run the test in a clean environment
**System information (please complete the following information):**
 - OS: [e.g. MacOS 10.15.6]
 - Compiler: [Apple-Clang 11.0.3]
 - Environment: [FairSoft dev]

**Comment by dennisklein** [comment]
fixed by 32b25f3249
